// js/lang/xhrpg_lang_vi.js — Tiếng Việt dict (lazy-load โดย _ensureLangLoaded ใน canvas.js) · คีย์ = ไทย byte-exact ห้ามแก้
// _VI_KNIFE_S ต้องตรง byte-exact กับ _LOG_KNIFE_S ใน canvas.js (ใช้ประกอบคีย์ onboarding)
var _VI_KNIFE_S = '<svg viewBox="0 0 32 32" width="15" height="15" style="vertical-align:-3px;filter:drop-shadow(0 0 0.7px rgba(255,255,255,0.55))"><g stroke="#1e293b" stroke-width="1.6" stroke-linejoin="round"><path d="M16 4 L19 18 L13 18 Z" fill="#dbe2ea"/><rect x="9" y="17" width="14" height="3" rx="1.4" fill="#f5b53c"/><rect x="13.2" y="20" width="5.6" height="8.4" rx="1.8" fill="#8a5636"/></g></svg>';
window.XHRPG_I18N.vi = {
  // ── Thêm bản dịch cho chức năng PK / Xem thông tin đối thủ (Inspect) ──
  'ของสวมใส่': 'Trang bị',
  'ของหายาก': 'Vật phẩm hiếm',
  'ไข่': 'Trứng',
  'ยังไม่มี': 'Chưa sở hữu',
  'ยังไม่ได้สวมใส่อะไรเลย': 'Chưa trang bị gì cả',
  'ของสะสมทั้งหมด': 'Tất cả đồ sưu tầm',
  'รวมทั้งหมด': 'Tổng cộng',
  'โมดูลที่ติดตั้ง': 'Module đã lắp',
  'โมดูลโล่': 'Module khiên',
  'แกนโล่': 'Lõi khiên',
  'ชิ้นส่วนไททัน': 'Linh kiện Titan',
  'ชิ้นส่วนยานบิน': 'Linh kiện phi thuyền',
  'หมวกเกราะ': 'Mũ giáp',
  'ชุดเกราะ': 'Giáp ngực',
  'รองเท้าเกราะ': 'Giày giáp',
  'สร้อยพลัง': 'Dây chuyền sức mạnh',
  'แหวนพลัง': 'Nhẫn sức mạnh',

  // ── Tùy chọn trang bị / Option lines (EQ2_OPT_TXT) ──
  'ระยะมีดสั้น +{v}m': 'Tầm dao găm +{v}m',
  'ระยะมีดยาว +{v}m': 'Tầm dao dài +{v}m',
  'ความจุมีดสั้น +{v}': 'Sức chứa dao găm +{v}',
  'ธนูไททัน ATK +{v}': 'ATK cung Titan +{v}',
  'ขวานไททัน ATK +{v}': 'ATK rìu Titan +{v}',
  'Robot Energy +{v}': 'Năng lượng Robot +{v}',
  'ระยะ Titan Beam +{v}m': 'Tầm Titan Beam +{v}m',
  'DMG Railgun ยานบิน +{v}': 'DMG Railgun phi thuyền +{v}',
  'ระยะ Railgun ยานบิน +{v}m': 'Tầm Railgun phi thuyền +{v}m',
  'ความเร็วเดิน +{v}%': 'Tốc độ di chuyển +{v}%',
  'ATK ดาบ +{v}%': 'ATK kiếm +{v}%',
  'ระยะดาบ +{v}m': 'Tầm kiếm +{v}m',
  'ATK ป้อม +{v}%': 'ATK pháo tháp +{v}%',
  'ระยะป้อม +{v}m': 'Tầm pháo tháp +{v}m',
  'ATK มีดขว้าง +{v}%': 'ATK phi dao +{v}%',
  'เกราะสูงสุด +{v}%': 'Giáp tối đa +{v}%',
  'ฟื้น HP +{v}%/วิ': 'Hồi HP +{v}%/s',
  'ธนูไททัน SHOCK +{v}s': 'Cung Titan SHOCK +{v}s',
  'ขวานไททัน STUN +{v}s': 'Rìu Titan STUN +{v}s',
  '🧲 ดึงมอน (สกิล) +{v} ตัว': '🧲 Kéo quái (Kỹ năng) +{v} con',
  '🤖 ดึงมอน (ไททัน) +{v} ตัว': '🤖 Kéo quái (Titan) +{v} con',
  'ลดคูลดาวน์สกิล +{v}%': 'Giảm CD kỹ năng +{v}%',
  '🪵 ไม้ดรอป +{v}': '🪵 Gỗ rơi +{v}',
  '🪨 หินดรอป +{v}': '🪨 Đá rơi +{v}',
  '⚙️ เหล็กดรอป +{v}': '⚙️ Sắt rơi +{v}',
  '🟫 ทองแดงดรอป +{v}': '🟫 Đồng rơi +{v}',
  '🌿 สมุนไพรดรอป +{v}': '🌿 Thảo dược rơi +{v}',

  // ── เมนูล่าง ──
  'อาวุธ':'Vũ khí', 'ไอเทม':'Vật phẩm', 'STAT ทักษะ':'Chỉ số/Kỹ năng', 'ผู้ติดตาม':'Đồng hành', 'ยานบิน':'Phi thuyền',
  'การ์ด':'Thẻ bài', 'ตลาด':'Chợ', 'สัตว์เลี้ยง':'Thú cưng', 'อันดับ':'Xếp hạng',
  // ── หัว popup ──
  '🐾 สัตว์เลี้ยง':'🐾 Thú cưng', '🎴 สมุดสะสมการ์ด':'🎴 Bộ sưu tập thẻ bài', '⚔ อาวุธ':'⚔ Vũ khí', '🎒 ไอเทม':'🎒 Vật phẩm',
  '🐱 ผู้ติดตาม':'🐱 Đồng hành', '🛸 ยานบิน':'🛸 Phi thuyền', '🏆 อันดับผู้เล่น':'🏆 Xếp hạng người chơi',
  '📜 บันทึกเหตุการณ์':'📜 Nhật ký sự kiện', '📖 คู่มือการเล่น':'📖 Cẩm nang chơi game', '🏪 ตลาด':'🏪 Chợ', '📊⚡ STAT ทักษะ':'📊⚡ Chỉ số & Kỹ năng',
  // ── ปุ่ม HUD/แถบบน ──
  '📖 บันทึก':'📖 Nhật ký', '🗺️ แผนที่':'🗺️ Bản đồ', 'รัศมีสำรวจ':'Bán kính khám phá', '⬅ ออกจากเกม':'⬅ Thoát game',
  'เข้าสู่ระบบด้วย':'Đăng nhập bằng', 'บันทึก':'Lưu', 'ชื่อในเกม (2–16 ตัว)':'Tên trong game (2–16 ký tự)',
  '🗺️ เลือกจุดหมาย':'🗺️ Chọn điểm đến', 'ออนไลน์':'Online', 'เสียง':'Âm thanh', 'เกราะ':'Giáp',
  'อันดับผู้เล่น(แท็บ)':'🏆 Người chơi',
  // ── หน้าเติมเงิน ──
  'เติม P Points':'Nạp P Points', '🎁 แอดมินเติมให้':'🎁 Admin tặng', 'โบนัสสูงสุด +100%':'Thưởng tối đa +100%', 'เลือกภาษา':'Chọn ngôn ngữ',
  'กล่องสุ่มโมดูล':'Hộp Module', 'กล่องสุ่มการ์ด':'Hộp thẻ bài',
  'มีด':'Kiếm', 'ไททัน':'Titan', 'ธนูไททัน':'Cung Titan', 'ป้อม':'Pháo tháp',
  'PROMOTION — เติมครั้งแรกของเดือน รับ P ×1.5!':'PROMOTION — Nạp lần đầu trong tháng nhận P ×1.5!',
  'แพคไหนก็ได้ รับไปเลย 1.5 เท่า · เดือนละ 1 ครั้ง · ขึ้นเดือนใหม่รับสิทธิอีกครั้ง':'Gói nào cũng được · ×1.5 P · mỗi tháng 1 lần · sang tháng mới nhận lại ưu đãi',
  'โปร ×1.5 เดือนนี้ใช้สิทธิแล้ว — ขึ้นเดือนใหม่รับสิทธิอีกครั้ง':'Khuyến mãi ×1.5 tháng này đã dùng — sang tháng mới sẽ có lại',
  'คุ้มสุด':'HỜI NHẤT', 'รับจริง {n} P (×1.5)':'Nhận {n} P (×1.5)', 'ถูกที่สุด':'giá tốt nhất', 'ขายดี':'Bán chạy', 'รับ':'Nhận',
  'เกิดข้อผิดพลาด: ':'Lỗi: ', 'ไม่สามารถเชื่อมต่อ Stripe ได้':'Không thể kết nối Stripe',
  // ── ชื่อโซน/แมพ (HUD) ──
  '🌿 ทุ่งกลาง':'🌿 Cánh đồng trung tâm', '🌲 ป่ารอบนอก':'🌲 Rừng ngoại vi', '⛰️ เชิงเขา':'⛰️ Chân núi', '🏔️ แดนไกล':'🏔️ Miền xa xôi', '🌋 สุดขอบแดน':'🌋 Tận cùng thế giới',
  '🏜️ ทะเลทรายนิรันดร์':'🏜️ Sa mạc vĩnh hằng', '❄️ ดินแดนเยือกแข็ง':'❄️ Vùng đất băng giá',
  // ── แผง STAT ──
  'ทักษะ':'Kỹ năng', 'ใส่แต้มทั้งหมด {n} pt ลง {s}?':'Dồn hết {n} điểm vào {s}?',
  'ค่าที่ได้รับจากสเตตัส (รวมอุปกรณ์/โมดูล)':'Hiệu quả từ chỉ số (gồm trang bị/Module)',
  'ATK ดาบ (melee) {a} · 🛡️ เกราะ {b} · 💥 Crit {c} <i>(รวมกับ LUK)</i>':'ATK kiếm (cận chiến) {a} · 🛡️ Giáp {b} · 💥 Crit {c} <i>(cộng với LUK)</i>',
  'หลบมอน Lv.1 {a} (เพดาน 75% · MVP ครึ่ง) · เดินเร็วขึ้น · ⏱️ ลด CD สกิล {b} (สูงสุด 50% ที่ AGI 300)':'Né quái Lv.1 {a} (tối đa 75% · MVP giảm nửa) · đi nhanh hơn · ⏱️ giảm CD kỹ năng {b} (tối đa 50% ở AGI 300)',
  'ATK มีดสั้น {a} · มีดยาว {b} · ระยะขว้าง {c}':'ATK dao găm {a} · Dao dài {b} · Tầm ném {c}',
  'MP สูงสุด {a} · MP ฟื้น {b}/s · พลังงานไททัน {c}/s · ATK ป้อม {d}':'MP tối đa {a} · Hồi MP {b}/s · Năng lượng Titan {c}/s · ATK pháo tháp {d}',
  'HP สูงสุด {a} · 🔰 DEF {b} · เกราะสูงสุด {c} · เกราะฟื้น {d}/s · HP ฟื้น {e}/s · ความจุยา {f}/tier':'HP tối đa {a} · 🔰 DEF {b} · Giáp tối đa {c} · Hồi giáp {d}/s · Hồi HP {e}/s · Sức chứa thuốc {f}/tier',
  '💥 Crit ×2 {a} <i>(LUK+STR)</i> · โอกาสดรอปทรัพยากร {b} (เพดาน 48% · ไม้ ×2) · โบนัสจำนวน {c} <i>(ทรัพยากร/สมุนไพร)</i>':'💥 Crit ×2 {a} <i>(LUK+STR)</i> · Tỷ lệ rơi tài nguyên {b} (tối đa 48% · gỗ ×2) · Thưởng số lượng {c} <i>(tài nguyên/thảo dược)</i>',
  '30% ลุ้น +1..':'30% cơ hội +1..',
  // ── สกิล (renderSkills) ──
  'คงเหลือ':'còn lại', '{a}/{b} แต้ม':'{a}/{b} điểm', '{a} สกิล':'{a} kỹ năng',
  '🔒 ล็อค':'🔒 Khóa', '✓ เต็ม':'✓ Max', '+ อัพ':'+ Nâng', '✓ เปิด':'✓ Bật', '✕ ปิด':'✕ Tắt',
  '📊 ตอนนี้':'📊 Hiện tại', '⬆ ต่อ Lv':'⬆ Mỗi Lv', '🔓 ปลดล็อก:':'🔓 Mở khóa:', '🎯 ระยะ':'🎯 Tầm',
  'ต้นสาย (ไม่มีเงื่อนไข)':'Gốc nhánh (không điều kiện)', 'เลเวล {a}':'Cấp {a}',
  'ไม่สามารถอัพสกิลได้':'Không thể nâng kỹ năng', 'ไม่สามารถเปลี่ยนสถานะสกิลได้':'Không thể bật/tắt kỹ năng', 'ใช้สกิลไม่ได้':'Không thể dùng kỹ năng',
  // ── ชื่อสาย/แท็บสกิล ──
  '⚔ สาย ATK — มีดขว้าง':'⚔ Nhánh ATK — Phi dao', '🛡 สาย DEF — ความอึด':'🛡 Nhánh DEF — Độ bền',
  '🗡 สายระยะประชิด — ดาบ':'🗡 Nhánh cận chiến — Kiếm', '🗼 สายป้อมปืน — ป้อมปืน':'🗼 Nhánh pháo tháp — Pháo tháp',
  'มีดขว้าง':'Phi dao', 'ความอึด':'Độ bền', 'ดาบ':'Kiếm', 'ป้อมปืน':'Pháo tháp',
  // ── ชื่อสกิล ──
  'ขว้างจุดตาย':'Ném chí mạng', 'มีดขว้างสายฟ้า':'Phi dao sấm sét', 'มีดขว้างระเบิด':'Phi dao nổ', 'สามมีดทะลวง':'Tam dao xuyên phá',
  'ร่างกายแกร่ง':'Thân thể cứng cáp', 'เพิ่มเกราะ':'Tăng giáp', 'ฟื้น HP':'Hồi HP', 'ดึงมอน':'Kéo quái',
  'ฝึกดาบ':'Luyện kiếm', 'แทงรอบตัว':'Đâm xoay vòng', 'ดาบกางเขน':'Kiếm thập tự', 'ดาบ X':'Kiếm chữ X',
  'เสริมพลังป้อม':'Cường hóa pháo tháp', 'ป้อมคงทน':'Pháo tháp bền bỉ', 'ป้อมคู่':'Pháo tháp đôi', 'ป้อมปืนใหญ่':'Pháo tháp đại bác',
  // ── ต่อ Lv (perLv) ──
  '+5 ATK มีด(สั้นยาว)':'+5 ATK dao (găm/dài)', 'ตัวคูณ DMG +0.1×':'Hệ số DMG +0.1×', '+1m รัศมี':'+1m bán kính',
  '+0.2× DMG ที่เป้าล็อก':'+0.3× DMG lên mục tiêu bị khóa', '+0.3× DMG รวม':'+0.3× tổng DMG', '+10 HP สูงสุด':'+10 HP tối đa',
  '+5 เกราะ · ฟื้น +1/s':'+5 giáp · hồi +1/s', '+5m ระยะดึง':'+5m tầm kéo', '+2% สะท้อน':'+2% phản dame',
  '— (สเกลตาม ATK มอนที่สะสม)':'— (theo ATK quái tích lũy)', '+6 ATK ดาบ':'+6 ATK kiếm',
  '+0.1× DMG/หมัด':'+0.1× DMG/đòn', '+0.1× DMG/เป้า':'+0.1× DMG/mục tiêu', 'ATK ป้อม +5 · ระยะ +1m':'ATK pháo tháp +5 · tầm +1m',
  '+1s อายุป้อม':'+1s thời gian pháo tháp', 'ระยะป้อม +1m':'Tầm pháo tháp +1m', '+1m รัศมีออร่า':'+1m bán kính hào quang',
  '+0.1× DMG · +1m รัศมีระเบิด':'+0.1× DMG · +1m bán kính nổ',
  // ── ระยะ (rng) ──
  'ตามมีด(สั้นยาว)':'Theo dao (găm/dài)', 'ระยะดาบ':'Tầm kiếm', 'ตามป้อม':'Theo pháo tháp', '{a}m รอบป้อม':'{a}m quanh pháo tháp',
  // ── รายละเอียด (xtra) ──
  'ชิ่ง 3 ตัว · ลดหลั่น 100/80/60%':'Nảy 3 mục tiêu · giảm dần 100/80/60%',
  'AOE · {a}มีด(สั้นยาว)×3':'AOE · {a}dao (găm/dài) ×3',
  'ล็อกจนเป้าตาย · MP 5/การล็อก':'Khóa đến khi mục tiêu chết · MP 5/lần khóa',
  'มีด 3 เล่มวิถีโค้งม่วง · ใช้มีด 3':'3 dao bay theo quỹ đạo cong tím · tốn 3 dao',
  'ดึงครึ่งระยะ · รวม MVP':'Kéo lại nửa khoảng cách · gồm cả MVP',
  'มอนตีเรา/ไททัน/สัตว์เลี้ยง = สะท้อนใส่มอนใกล้สุด · ไม่ใช้ MP':'Quái đánh bạn/Titan/thú cưng = phản dame lên quái gần nhất · không tốn MP',
  'สะสม ATK มอนที่ตีทีมเรา 5 วิ + VIT×5 → ระเบิดใส่เป้าเดี่ยว':'Tích ATK quái đánh đội bạn trong 5s + VIT×5 → nổ vào một mục tiêu',
  'ฟันดาบ 2 ครั้ง':'Chém 2 nhát', '≤3 เป้า':'≤3 mục tiêu',
  'ฟันไขว้กางเขน เป้าเดี่ยว':'Chém thập tự, đơn mục tiêu', 'ฟันไขว้ X เป้าเดี่ยว':'Chém chữ X, đơn mục tiêu',
  'ป้อมฐาน 20 · +3 ATK/INT':'Pháo tháp gốc 20 · +3 ATK/INT', 'ปัก 2 ป้อม':'Đặt 2 pháo tháp',
  'DMG = ATK ป้อม ×{b} ทุกวิ · ค่าปัก +20 MP/ต้น · ป้อมคู่ได้ทั้งคู่':'DMG = ATK pháo tháp ×{b} mỗi giây · phí đặt +20 MP/trụ · pháo tháp đôi hưởng cả hai',
  'อายุ 60s · ยิง 1 นัด/วิ ใช้กระสุนมีดยาว · ปักหลัง Hero · MP 100/ปัก':'Tồn tại 60s · bắn 1 phát/giây dùng đạn dao dài · đặt sau lưng Hero · MP 100/lần đặt',
  // ── สถานะปัจจุบัน (statLabel) ──
  'ATK มีด(สั้นยาว) +{a}':'ATK dao (găm/dài) +{a}',
  'DMG ×{a} (ต่อตัว) · ชิ่ง 3 ตัว':'DMG ×{a} (mỗi mục tiêu) · nảy 3 mục tiêu',
  'รัศมี {a}m · DMG 1.5× มีด(สั้นยาว)':'Bán kính {a}m · DMG 1.5× dao (găm/dài)',
  'เป้าล็อกรับ DMG มีดขว้าง ×{a}':'Mục tiêu bị khóa nhận DMG phi dao ×{a}',
  'DMG รวม ×{a}':'Tổng DMG ×{a}', 'HP สูงสุด +{a}':'HP tối đa +{a}',
  'เกราะ +{a} · ♻️+{b}/s':'Giáp +{a} · ♻️+{b}/s', 'ฟื้น +{a} HP/s':'Hồi +{a} HP/s',
  'ระยะดึง {a}m':'Tầm kéo {a}m', 'สะท้อน {a}% ATK มอน + VIT×2':'Phản {a}% ATK quái + VIT×2',
  'ระเบิด = ATK สะสม 5 วิ + VIT×5':'Nổ = ATK tích 5s + VIT×5',
  'ATK ดาบ +{a}':'ATK kiếm +{a}', 'ATK ×{a}/หมัด':'ATK ×{a}/đòn', 'ATK ×{a}/เป้า':'ATK ×{a}/mục tiêu',
  'DMG = ATK ดาบ ×{a}':'DMG = ATK kiếm ×{a}', 'ป้อม +{a} ATK':'Pháo tháp +{a} ATK', 'ป้อมอยู่ {a}s':'Pháo tháp tồn tại {a}s',
  '2 ป้อม · ระยะ +{a}m':'2 pháo tháp · tầm +{a}m',
  'ออร่าไฟฟ้า {a}m · ATK ป้อม ×{b}/วิ':'Hào quang điện {a}m · ATK pháo tháp ×{b}/giây',
  'DMG = ATK ป้อม ×{a} · ระเบิด {b}m':'DMG = ATK pháo tháp ×{a} · nổ {b}m',
  // ── คู่มือสกิล (SKILL_HELP_DATA) ──
  'ขว้างจุดตาย (Passive)':'Ném chí mạng (Passive)', 'มีดขว้างสายฟ้า (Action)':'Phi dao sấm sét (Action)',
  'ร่างกายแกร่ง (Passive)':'Thân thể cứng cáp (Passive)', 'เพิ่มเกราะ (Passive)':'Tăng giáp (Passive)',
  'ฟื้น HP (Passive)':'Hồi HP (Passive)', 'ดึงมอน (Action)':'Kéo quái (Action)',
  'เพิ่ม ATK มีด(สั้นยาว) ถาวร +5 ต่อ Lv.\nLv1 = +5 … Lv10 = +50 ATK':'Tăng vĩnh viễn ATK dao (găm/dài) +5 mỗi Lv.\nLv1 = +5 … Lv10 = +50 ATK',
  'Chain Lightning ⚡ ชิ่ง 3 เป้า · ต้องการ ขว้างจุดตาย Lv.5 — MP 10 CD 5s\nDMG = ATK มีด(สั้นยาว) ×2.1 ถึง ×3.0 ตาม Lv.':'Chain Lightning ⚡ nảy 3 mục tiêu · cần Ném chí mạng Lv.5 — MP 10 CD 5s\nDMG = ATK dao (găm/dài) ×2.1 đến ×3.0 theo Lv.',
  'อัพแล้วได้เลย ไม่ต้องกด ไม่ใช้ MP\nHP สูงสุด +30 ต่อ Lv. (Lv.10 = +300 HP)':'Nâng là có ngay, không cần bấm, không tốn MP\nHP tối đa +30 mỗi Lv. (Lv.10 = +300 HP)',
  'ต้องการ ร่างกายแกร่ง Lv.3\nPassive บวกติดตัว: เกราะสูงสุด +5/Lv + ♻️ ฟื้นเกราะ +1/Lv ต่อวินาที (ไม่ใช้ MP)':'Cần Thân thể cứng cáp Lv.3\nPassive thường trực: giáp tối đa +5/Lv + ♻️ hồi giáp +1/Lv mỗi giây (không tốn MP)',
  'ต้องการ ร่างกายแกร่ง Lv.5\nPassive บวกติดตัว: ฟื้น HP +1/Lv ต่อวินาที (บวกกับ regen ปกติ ไม่ใช้ MP)':'Cần Thân thể cứng cáp Lv.5\nPassive thường trực: hồi HP +1/Lv mỗi giây (cộng với hồi phục thường, không tốn MP)',
  'ปลดล็อก Lv.30 + ฟื้น HP Lv.5 + เพิ่มเกราะ Lv.5 · Auto · MP 10 · CD ~10s\nดึงมอนทุกตัวในระยะให้วิ่งเข้าหาผู้เล่น เข้าครึ่งระยะต่อครั้ง (รวม MVP)\nระยะดึง 75m +5m ต่อ Lv (Lv.1=80m … Lv.10=125m)':'Mở khóa ở Lv.30 + Hồi HP Lv.5 + Tăng giáp Lv.5 · Auto · MP 10 · CD ~10s\nKéo mọi quái trong tầm chạy về phía người chơi, mỗi lần kéo nửa khoảng cách (gồm cả MVP)\nTầm kéo 75m +5m mỗi Lv (Lv.1=80m … Lv.10=125m)',
  'ได้ 1 point ทุกครั้งที่ Level Up\nใช้อัพ Skill ได้ที่นี่ แยกจาก STAT Point':'Nhận 1 điểm mỗi lần Level Up\nDùng nâng Skill tại đây, tách riêng với điểm STAT',
  // ── อาวุธ (renderGuns/modules) ──
  // ── แท็บ + การ์ดอาวุธ ──
  'อาวุธขว้าง':'Phi dao', '🗼 ป้อม':'🗼 Pháo tháp', '🛡️ เกราะ':'🛡️ Giáp',
  'วัสดุเคลือบ มีดสั้น':'Lớp phủ: Dao găm', 'วัสดุเคลือบ มีดยาว':'Lớp phủ: Dao dài',
  'วัสดุเคลือบ ดาบ':'Lớp phủ: Kiếm', 'วัสดุเคลือบ ป้อมปืน':'Lớp phủ: Pháo tháp',
  'ATK {a} | ระยะ {b}m | 🎒 {c} นัด':'ATK {a} | Tầm {b}m | 🎒 {c} viên',
  'ระยะ {a}m (อัตโนมัติ)':'Tầm {a}m (tự động)', '(+{a} โมดูล)':'(+{a} Module)', '💨 หลบ +20%':'💨 Né +20%',
  'ใช้งาน':'Đang dùng', 'เติมอัตโนมัติ':'Tự nạp đạn',
  // ── เกราะ ──
  'ความชำนาญ เกราะ':'Tinh thông giáp', '🛡️ รับดาเมจก่อน HP':'🛡️ Đỡ sát thương trước HP',
  'DEF — ลดดาเมจ':'DEF — giảm sát thương', 'หักดาเมจตรงๆ <b>ก่อน</b>เข้าเกราะ':'Trừ thẳng sát thương <b>trước</b> khi vào giáp',
  ' · 🔰 โมดูล +{a}':' · 🔰 Module +{a}', '🛡️ สูงสุด':'🛡️ Tối đa', '♻️ ฟื้นเกราะ':'♻️ Hồi giáp', '💚 ฟื้น HP':'💚 Hồi HP',
  'เกราะ +{a}':'Giáp +{a}', 'ฟื้น +{a}/วิ':'Hồi +{a}/s', 'สะท้อน {a}%':'Phản {a}%',
  'อัพ/Lv = สูงสุด +10 · 🔰DEF +1 · ♻️ฟื้น +1 · 💚HP +1/5Lv':'Mỗi Lv: tối đa +10 · 🔰DEF +1 · ♻️hồi +1 · 💚HP +1/5Lv',
  'อัพเกรดเกราะไม่ได้':'Không thể nâng cấp giáp',
  // ── ป้อมปืน ──
  'ATK <b>{a}</b> | ระยะ <b>{b}m</b> | 🔵 ใช้กระสุนมีดสั้น':'ATK <b>{a}</b> | Tầm <b>{b}m</b> | 🔵 dùng đạn dao găm',
  'ปักอัตโนมัติเมื่อเจอมอน · {t}อายุ {a}s · MP 20/ป้อม':'Tự đặt khi gặp quái · {t}tồn tại {a}s · MP 20/trụ',
  'ป้อมคู่ ×2 · ':'Pháo tháp đôi ×2 · ', '🔧 โมดูล: {a}':'🔧 Module: {a}',
  'ระยะ +{a}m':'Tầm +{a}m', 'อายุ +{a}s':'Thời gian +{a}s',
  'สูงสุด Lv.{a} ที่ผู้เล่น Lv.{b}':'Tối đa Lv.{a} khi người chơi Lv.{b}',
  '💡 เพิ่มพลังป้อม (+ATK/Lv) ที่สกิล {a} เมนู STAT · INT +3 ATK/แต้ม':'💡 Tăng sức mạnh pháo tháp (+ATK/Lv) ở kỹ năng {a} trong menu STAT · INT +3 ATK/điểm',
  '🗼 กระสุนป้อม — เปิดหลาย tier ได้ (ยิง T สูงสุดที่มีกระสุนก่อน หมดแล้วไล่ลง)':'🗼 Đạn pháo tháp — bật được nhiều tier (bắn T cao nhất còn đạn trước, hết thì xuống dần)',
  // ── แถบกระสุน tier ──
  'ยานบิน Lv.{a}':'Phi thuyền Lv.{a}', 'เปิด':'Bật', 'ปิด':'Tắt', 'เปิดกล่อง':'Mở', 'ปิดหน้าต่าง':'Đóng',
  'ปลดล็อก Lv.{a}':'Mở khóa ở Lv.{a}', 'จุ {a} นัด':'Chứa {a} viên', 'ไม่มีมีดสั้น':'Hết dao găm',
  'มีดสั้นที่ใช้: {i} T{t} — {d}':'Dao găm đang dùng: {i} T{t} — {d}',
  // ── โมดูล: หัวแผงต่ออาวุธ ──
  'โมดูลมีดสั้น':'Module dao găm', 'โมดูลมีดยาว':'Module dao dài', 'โมดูลมีด':'Module dao', 'โมดูลขวาน':'Module rìu',
  'โมดูลไททัน (แกนพลังงาน)':'Module Titan (lõi năng lượng)', 'โมดูลธนูไททัน (ARM)':'Module cung Titan (ARM)',
  'โมดูล Premium Titan Beam':'Module Premium Titan Beam', 'โมดูลเกราะ':'Module giáp',
  'โมดูลยานบิน (แกนพลังงาน)':'Module phi thuyền (lõi năng lượng)', 'โมดูลป้อม':'Module pháo tháp',
  // ── โมดูล: ระดับความหายาก (รวมชื่อกล่องสุ่ม) ──
  'ทั่วไป':'Thường', 'ซับซ้อน':'Cao cấp', 'หายาก':'Hiếm', 'ขั้นสูง':'Sử thi',
  'ขั้นสูงพิเศษ':'Sử thi+', 'ขั้นตำนาน':'Huyền thoại', 'ตำนานพิเศษ':'Thần thoại',
  // ── โมดูล: ชื่อช่อง ──
  'ใบมีด':'Lưỡi dao', 'ศูนย์เล็ง':'Ống ngắm', 'ด้ามจับ':'Tay cầm', 'ใบขวาน':'Lưỡi rìu', 'ด้าม':'Cán', 'ลำกล้อง':'Nòng súng', 'คม':'Lưỡi',
  'คมมีดสั้น':'Lưỡi dao găm', 'คมมีดยาว':'Lưỡi dao dài', 'คมมีด':'Lưỡi dao', 'คมขวาน':'Lưỡi rìu',
  'แกนพลังงาน':'Lõi năng lượng', 'แกนลำแสง':'Lõi tia sáng',
  'แกนหลัง':'Lõi lưng', 'แกนสมอง':'Lõi não', 'แกนกลาง':'Lõi trung tâm',
  'แกนเกราะ':'Lõi giáp', 'แกนฟื้นฟู':'Lõi hồi phục', 'แกนสะท้อน':'Lõi phản dame',
  'โมดูลหลังคา':'Module mái', 'โมดูลกำแพง':'Module tường', 'โมดูลพื้น':'Module sàn',
  'แกนโจมตี':'Lõi tấn công', 'แกนเล็ง':'Lõi ngắm bắn', 'แกนคงทน':'Lõi bền bỉ',
  // ── โมดูล: คำอธิบายช่องว่าง (stat) ──
  '⚡ พลังงาน + 🔋 recover':'⚡ Năng lượng + 🔋 recover', '⚡ พลังงาน':'⚡ Năng lượng',
  '+เกราะสูงสุด':'+Giáp tối đa', '+ฟื้นเกราะ/วิ':'+Hồi giáp/s', 'สะท้อนดาเมจ %':'Phản sát thương %',
  '+ATK (รวมโมดูล)':'+ATK (tổng Module)', '+ระยะ 1m/Lv · +ATK':'+Tầm 1m/Lv · +ATK', '+อายุ 0.5s/Lv · +ATK':'+Thời gian 0.5s/Lv · +ATK',
  'ระยะเอื้อม + ATK':'Tầm với + ATK', 'ระยะฟัน + ATK':'Tầm chém + ATK', 'ระยะ + ATK':'Tầm + ATK',
  // ── โมดูล: เอฟเฟกต์ที่สวมแล้ว ──
  '🛡️ เกราะสูงสุด +{a} · 🔰 DEF +{b}':'🛡️ Giáp tối đa +{a} · 🔰 DEF +{b}',
  '♻️ ฟื้นเกราะ +{a}/วิ · 🔰 DEF +{b}':'♻️ Hồi giáp +{a}/s · 🔰 DEF +{b}',
  '⚡ สะท้อน {a}% · 🔰 DEF +{b}':'⚡ Phản {a}% · 🔰 DEF +{b}',
  '⚡ พลังงานสูงสุด +{a} · 🔋 recover +{a}/s':'⚡ Năng lượng tối đa +{a} · 🔋 recover +{a}/s',
  '⚡ พลังงานสูงสุด +{a} · 🔋 recover +{a}/s · 🔰 DEF +{b}':'⚡ Năng lượng tối đa +{a} · 🔋 recover +{a}/s · 🔰 DEF +{b}',
  '⚡ พลังงาน +{a}':'⚡ Năng lượng +{a}',
  '⚔️ ATK +{a} (รวมโมดูล)':'⚔️ ATK +{a} (tổng Module)',
  '🔭 ระยะยิง +{a}m · ⚔️ ATK +{b}':'🔭 Tầm bắn +{a}m · ⚔️ ATK +{b}',
  '⏳ อายุป้อม +{a}s · ⚔️ ATK +{b}':'⏳ Thời gian pháo tháp +{a}s · ⚔️ ATK +{b}',
  'ระยะเอื้อม +{a}m · ATK +{b}':'Tầm với +{a}m · ATK +{b}', 'ระยะฟัน +{a}m · ATK +{b}':'Tầm chém +{a}m · ATK +{b}',
  'ระยะ +{a}m · ATK +{b}':'Tầm +{a}m · ATK +{b}',
  'ระยะเอื้อม +{a}m':'Tầm với +{a}m', 'ระยะฟัน +{a}m':'Tầm chém +{a}m',
  'ฟื้น +{a} · 🔰+{b}':'Hồi +{a} · 🔰+{b}', 'สะท้อน {a}% · 🔰+{b}':'Phản {a}% · 🔰+{b}',
  // ── โมดูล: แผง/คลัง/จัดการ ──
  'ว่าง':'Trống', '— ว่าง —':'— trống —', 'ถอด':'Tháo',
  'เลือกแล้ว {a} ชิ้น (แตะเพื่อเลือก)':'Đã chọn {a} món (chạm để chọn)', '☐ ล้าง':'☐ Bỏ chọn', '☑ ทั้งหมด':'☑ Tất cả',
  'ยกเลิก':'Hủy', '🗑️ ทำลายที่เลือก ({a})':'🗑️ Phá hủy đã chọn ({a})',
  'คลังโมดูล {a}/30 (แตะติดตั้ง)':'Kho Module {a}/30 (chạm để lắp)', '🗑️ จัดการ':'🗑️ Quản lý',
  '♻️ ทำลายแล้ว <b>{a} เพชรที่ตีบวก + 🎴 การ์ดที่เสียบ คืนเข้าคลังทั้งหมด</b>':'♻️ Phá hủy sẽ hoàn <b>{a} kim cương cường hóa + 🎴 thẻ đã khảm về kho toàn bộ</b>',
  '(ยอดที่จะได้คืนแสดงตอนกดยืนยัน)':'(số lượng hoàn trả hiển thị khi xác nhận)',
  'ดูการ์ดในโมดูล ({a} ใบ)':'Xem thẻ trong Module này ({a})',
  'ยืนยันทำลาย {a} ชิ้น?':'Xác nhận phá hủy {a} món?',
  'ทำลายแล้วกู้คืนไม่ได้ (เพชรที่ตีบวก + การ์ดที่เสียบ คืนเข้าคลัง)':'Phá hủy không thể khôi phục (kim cương cường hóa + thẻ đã khảm được hoàn về kho)',
  'ทำลายเลย':'Phá hủy', '💎 คืนเพชร':'💎 Hoàn kim cương', '🎴 คืนการ์ด {a} ใบเข้าคลัง':'🎴 Hoàn {a} thẻ về kho',
  'ทำลายโมดูลระดับนี้ (เฉพาะที่ตีบวก +0) ทั้งหมด?\nการ์ดที่เสียบอยู่จะถูกคืนเข้าคลัง':'Phá hủy tất cả Module bậc này (chỉ loại +0)?\nThẻ đã khảm sẽ được hoàn về kho',
  'ติดตั้งไม่ได้':'Không thể lắp', 'ถอดไม่ได้':'Không thể tháo', 'ตีบวกไม่ได้':'Không thể cường hóa', 'ทำลายไม่ได้':'Không thể phá hủy',
  // ── กล่องสุ่มโมดูล ──
  '📦 กล่องสุ่มโมดูล':'📦 Hộp Module', 'รวม {a} ใบ':'Tổng {a}',
  'เปิดสุ่มโมดูลระดับนั้น 1 ชิ้น (ทุกอาวุธ/ทุกช่อง)':'Mở nhận ngẫu nhiên 1 Module bậc đó (mọi vũ khí/mọi ô)',
  'เปิดกล่องไม่ได้':'Không thể mở hộp', 'เปิดกล่องโมดูล{a}!':'Đã mở hộp Module {a}!',
  '⚙️ ติดตั้งให้อัตโนมัติแล้ว':'⚙️ Đã tự động lắp', '🎒 เข้าคลังแล้ว (คลังเต็ม)':'🎒 Đã vào kho (kho đầy)', '🎒 เข้าคลังแล้ว':'🎒 Đã vào kho',
  '🗑️ คลังเต็ม 30 → ทำลาย <b>{a} [{b}]</b> (ชิ้นต่ำสุด) แทน':'🗑️ Kho đầy (30) → đã phá hủy món thấp nhất <b>{a} [{b}]</b> thay thế',
  '💠 {a} รู · เพิ่ม [{b}]':'💠 {a} ô khảm · thêm [{b}]', 'รับแล้ว ✅':'Đã nhận ✅',
  // ── การ์ดในรูโมดูล ──
  'ถอด {a} G':'Gỡ {a} G', 'ถอดการ์ด (เลือกจ่าย G ตามระดับ / 19 P)':'Gỡ thẻ (trả G theo bậc / 19 P)',
  'เสียบการ์ด':'Khảm thẻ', '🎴 รู {a}/{b}':'🎴 Ô khảm {a}/{b}',
  '— ไม่มีการ์ดในคลัง —':'— không có thẻ trong kho —', '🎴 เลือกการ์ดเสียบ':'🎴 Chọn thẻ để khảm', '(เสียบถาวร)':'(khảm vĩnh viễn)',
  'ถอดการ์ดออกจากรู':'Gỡ thẻ khỏi ô khảm', 'การ์ดกลับเข้าคลัง · เลือกวิธีจ่าย':'Thẻ về kho · chọn cách trả phí',
  '(ระดับโมดูล {a})':'(bậc Module {a})', 'เสียบการ์ดไม่ได้':'Không thể khảm thẻ', 'ถอดการ์ดไม่ได้':'Không thể gỡ thẻ',
  '— รูว่าง —':'— ô trống —', '🎴 การ์ด {a}/{b} รู':'🎴 Thẻ {a}/{b} ô',
  // ── คู่มืออาวุธ (GUN_HELP) ──
  'มีดสั้น':'Dao găm', 'มีดยาว':'Dao dài', 'ดาบ (Sword)':'Kiếm', 'สลับอาวุธ':'Đổi vũ khí',
  'ชิ้นส่วนเสริมอาวุธ':'Linh kiện vũ khí', 'เติมกระสุนอัตโนมัติ':'Tự nạp đạn',
  'อาวุธหลักระยะกลาง ATK = 20+(Lv-1)×2\nระยะขว้างพื้นฐาน 35m (+1m ทุก DEX 24)\nความจุกระสุน T1 = 50 +5/เลเวลผู้เล่น (T สูงถือน้อยลง · ไม่ขึ้น STR แล้ว)\nมีดสั้นใช้ร่วมกับคลังยานบิน สลับอาวุธได้ที่ปุ่มด้านล่าง':'Vũ khí chính tầm trung, ATK = 20+(Lv-1)×2\nTầm ném cơ bản 35m (+1m mỗi 24 DEX)\nSức chứa đạn T1 = 50 +5/cấp người chơi (T cao mang ít hơn · không còn theo STR)\nDao găm dùng chung kho phi thuyền — đổi vũ khí bằng nút bên dưới',
  'ระยะขว้างไกล ATK = 120+(Lv-1)×5\nระยะขว้างพื้นฐาน 55m (+1m ทุก DEX 24)\nความจุกระสุน T1 = 50 +5/เลเวลผู้เล่น (T สูงถือน้อยลง · ไม่ขึ้น STR แล้ว)':'Ném tầm xa, ATK = 120+(Lv-1)×5\nTầm ném cơ bản 55m (+1m mỗi 24 DEX)\nSức chứa đạn T1 = 50 +5/cấp người chơi (T cao mang ít hơn · không còn theo STR)',
  'โจมตีระยะประชิด 5m ไม่ใช้กระสุน\nATK = (STR-5)×1 + 10 + (Lv-1)×8 ดีเมื่อกระสุนหมด':'Tấn công cận chiến 5m, không tốn đạn\nATK = (STR-5)×1 + 10 + (Lv-1)×8 — hữu ích khi hết đạn',
  'กดปุ่มสลับที่ด้านล่างเพื่อเลือกใช้ มีดสั้น / มีดยาว\nระบบจะขว้างอัตโนมัติตามอาวุธที่เลือก':'Bấm nút đổi bên dưới để chọn Dao găm / Dao dài\nGame sẽ tự ném theo vũ khí đã chọn',
  'ดรอปจากมอน → เพิ่มระยะขว้าง / ความจุกระสุน\nดูและสะสมได้ในเมนู 🎒 ไอเทม (รวมของสะสมทุกหมวด)':'Rơi từ quái → tăng tầm ném / sức chứa đạn\nXem và sưu tầm trong menu 🎒 Vật phẩm (gom mọi bộ sưu tập)',
  'เปิด checkmark เติมออโต้ → เมื่อกระสุน < 5 และยานบินมีกระสุนสำรอง จะวาร์ปกลับเติมทันที':'Bật ô tự nạp → khi đạn < 5 và phi thuyền còn đạn dự trữ, bạn dịch chuyển về nạp ngay',
  // ── ไอเทม/การ์ด/สัตว์เลี้ยง (renderItems/renderCard/renderPet) ──
  // ── แผงยา/เพชร (renderItems) ──
  'ยาฟื้นพลัง':'Thuốc hồi phục', 'ใช้ {i} +{h} HP':'Dùng {i} +{h} HP', 'ไม่มียา':'Hết thuốc',
  'ยาหมด → เดินกลับยานบินหยิบยาเอง (ปิด = พึ่งโดรน/แมวส่งอย่างเดียว)':'Hết thuốc → tự đi về phi thuyền lấy thuốc (tắt = chỉ nhờ drone/mèo giao hàng)',
  'ยาหมดกลับอัตโนมัติ':'Tự quay về khi hết thuốc',
  'เปิด/ปิดแต่ละ tier · ใช้ tier สูงสุดที่เปิดและมียา':'Bật/tắt từng tier · dùng tier cao nhất đang bật và còn thuốc',
  'AUTO เมื่อ HP &lt;':'AUTO khi HP &lt;', '✅ เปิด':'✅ Bật', '⛔ ปิด':'⛔ Tắt',
  'ใช้ T สูงสุดที่เปิดและมียา · &lt; 30% ใช้เสมอแม้ปิด AUTO':'Dùng T cao nhất đang bật và còn thuốc · &lt; 30% luôn uống kể cả tắt AUTO',
  '+{a} HP · จุ {b} ขวด':'+{a} HP · chứa {b} bình', ' · ใช้อยู่':' · đang dùng',
  'เพชร':'Kim cương', '(ตีบวกโมดูล)':'(cường hóa Module)',
  // ── หัวแผงของสะสม ──
  '🗃️ ของวิเศษ ของล้ำค่า':'🗃️ Bảo vật', '🗃️ ของวิเศษ อุปกรณ์สวมใส่':'🗃️ Trang bị',
  'ของวิเศษ ชิ้นส่วนสเตตัส':'Linh kiện chỉ số', 'ของวิเศษ ชิ้นส่วนอาวุธ':'Linh kiện vũ khí',
  'ของวิเศษ ชิ้นส่วนไททัน':'Linh kiện Titan', 'ของวิเศษ ชิ้นส่วนยานบิน':'Linh kiện phi thuyền',
  'ยังไม่ค้นพบ':'Chưa khám phá',
  // ── กล่องสุ่มการ์ด ──
  '🎁 กล่องสุ่มการ์ด':'🎁 Hộp thẻ bài', 'ระดับ {a}':'Bậc {a}',
  'เปิดสุ่ม<b>การ์ดมอน 1 ใบ</b>ตามช่วงเลเวลของกล่อง · โอกาสเป็นการ์ด <b style="color:#dc2626">⭐MVP 1%</b> · การ์ดเข้าสมุดทันที':'Mở nhận <b>1 thẻ quái ngẫu nhiên</b> theo khoảng cấp của hộp · tỷ lệ ra thẻ <b style="color:#dc2626">⭐MVP 1%</b> · thẻ vào bộ sưu tập ngay',
  '🎁 กล่องสุ่มการ์ด ระดับ {a} (Lv.{b}-{c})':'🎁 Hộp thẻ bài bậc {a} (Lv.{b}-{c})',
  'การ์ด {a}':'Thẻ {a}', '(คอมแบต)':'(chiến đấu)',
  '🎉 แจ็คพอต 1%! การ์ด ⭐MVP เข้าสมุดแล้ว':'🎉 Trúng jackpot 1%! Thẻ ⭐MVP đã vào bộ sưu tập',
  '✅ เข้าสมุดการ์ดแล้ว — เสียบโมดูล/สัตว์เลี้ยงได้ทันที':'✅ Đã vào bộ sưu tập thẻ — khảm ngay vào Module/thú cưng được',
  // ── สมุดสะสมการ์ด (renderCard) ──
  '✨ โบนัสสะสมการ์ด:':'✨ Thưởng sưu tập thẻ:', 'ทุก STAT':'mọi chỉ số', '({a} ชนิด)':'({a} loại)',
  'ทั้ง ATK/DEF/HP/MP':'cho ATK/DEF/HP/MP',
  'โบนัส':'Thưởng',
  '(ปกติ {n} · MVP {m})':'(thường {n} · MVP {m})',
  'โบนัสคอมแบต (เฉพาะการ์ด MVP เมื่อเสียบในโมดูล)':'Thưởng chiến đấu (chỉ thẻ MVP khi khảm trong Module)',
  'ยังไม่มีข้อมูลการ์ด — เข้าเกมสักครู่':'Chưa có dữ liệu thẻ — chơi một lát nhé',
  // ── สัตว์เลี้ยง (renderPet) ──
  '⏳ กำลังโหลดค่าพลังสัตว์เลี้ยง (จาก master)...':'⏳ Đang tải chỉ số thú cưng (từ master)...',
  '💫 สลบ':'💫 Gục', '💚 ฟื้น/วิ':'💚 Hồi/s',
  '🎯 แต้มอัพเกรด (Lv up +1)':'🎯 Điểm nâng cấp (+1 mỗi lần lên Lv)', '{a} แต้ม':'{a} điểm',
  '+ อัพ (1 แต้ม)':'+ Nâng (1 điểm)', 'ATK ×{a}/แต้ม':'ATK ×{a}/điểm', '+1 DEF/แต้ม':'+1 DEF/điểm', '+2 DEF/แต้ม':'+2 DEF/điểm',
  '💚 ฟื้นตัว':'💚 Hồi phục', '+0.20%/แต้ม':'+0.20%/điểm',
  'อัพเกรดไม่ได้':'Không thể nâng cấp', '❌ อัพเกรดไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Nâng cấp thất bại (không kết nối được server)',
  '🎴 การ์ดเสริมพลัง':'🎴 Thẻ tăng sức mạnh', '{a}/{b} รู':'{a}/{b} ô khảm',
  '🥚 สมุดสะสมไข่':'🥚 Bộ sưu tập trứng', '✨ โบนัสสะสมไข่:':'✨ Thưởng sưu tập trứng:',
  'ดรอปจากการกำจัดมอน/MVP · กดไข่ที่มีเพื่อฟัก (Lv.มอน × 100 G · MVP ×10)':'Rơi khi hạ quái/MVP · bấm trứng đang có để ấp (Lv. quái × 100 G · MVP ×10)',
  'มีสัตว์ฟักอยู่ — เก็บเข้าไข่ก่อนจึงฟักตัวใหม่ได้':'Đang có thú đã nở — thu về trứng trước rồi mới ấp con mới',
  'Lv.ต้นฉบับ {a}':'Lv. gốc {a}',
  '🥚 เก็บเข้าไข่ (10,000 G) — Lv(UP)/แต้มอัพเกรด รีเซ็ต · การ์ดคืนเข้าคลัง':'🥚 Thu về trứng (10,000 G) — Lv(UP)/điểm nâng cấp reset · thẻ hoàn về kho',
  'ยังไม่มีสัตว์เลี้ยง — กดไข่ในสมุดด้านล่างเพื่อฟัก':'Chưa có thú cưng — bấm trứng trong sổ bên dưới để ấp',
  'สัตว์จะเดินตามคุณ · ช่วยโจมตีมอน (ATK/HP ตาม master) · อัพเกรดได้เมื่อ Lv up · ใส่การ์ดได้ตามระดับมอน':'Thú cưng đi theo bạn · phụ đánh quái (ATK/HP theo master) · nâng cấp khi lên Lv · khảm thẻ theo cấp quái',
  'ยังไม่มีข้อมูลมอนสเตอร์ — เข้าเกมสักครู่':'Chưa có dữ liệu quái — chơi một lát nhé',
  'มีสัตว์เลี้ยงฟักอยู่แล้ว — เก็บเข้าไข่ก่อน (10,000 G)':'Đã có thú cưng nở rồi — thu về trứng trước (10,000 G)',
  'ฟักไข่ {a}?':'Ấp trứng {a}?', 'ค่าฟัก Lv.{a} × 100':'Phí ấp: Lv.{a} × 100',
  'เริ่มที่ Lv(UP) 1 · เดินตามคุณบนแผนที่':'Bắt đầu ở Lv(UP) 1 · đi theo bạn trên bản đồ', ' (ตัวใหญ่!)':' (to bự!)',
  '🐣 ฟักเลย':'🐣 Ấp luôn!', 'ฟักไข่':'Ấp trứng',
  'โบนัสอาวุธ Premium':'Thưởng vũ khí Premium',
  'รางวัลออฟไลน์ +10%':'Thưởng offline +10%',
  'มีผลกับรอบนี้':'đã áp dụng cho lần này',
  '(กำจัดมอนเร็วขึ้น → รางวัลด้านบนเพิ่มตามแล้ว)':'(Hạ quái nhanh hơn → đã tính vào phần thưởng ở trên)',
  'Reset STAT ฟรีวันละ 1 ครั้ง':'Reset STAT miễn phí 1 lần/ngày',
  'อยู่ล่างสุดของหน้า 🌟 PREMIUM':'Ở cuối trang 🌟 PREMIUM',
  'แชท':'Trò chuyện', 'แชทรวม':'Chung', 'แชทส่วนตัว':'Riêng', 'ฉัน':'Tôi',
  '💌 แชทส่วนตัว':'💌 Trò chuyện riêng', 'พิมพ์ข้อความ...':'Nhập tin nhắn...', 'ส่ง':'Gửi',
  'ยังไม่มีข้อความ — ทักทายกันได้เลย':'Chưa có tin nhắn — chào một câu nào!',
  'ยังไม่มีแชทส่วนตัว — กดที่ชื่อคนในแท็บ 🌐 รวม เพื่อเริ่มคุย':'Chưa có trò chuyện riêng — chạm vào tên ở tab 🌐 Chung để bắt đầu',
  'เก็บสัตว์เลี้ยงเข้าไข่? เสีย 10,000 G\nLv(UP) จะรีเซ็ตเป็น 1 · การ์ดที่เสียบคืนเข้าคลังฟรี · ไข่กลับเข้าสมุด':'Thu thú cưng về trứng? Tốn 10,000 G\nLv(UP) reset về 1 · thẻ đã khảm hoàn về kho miễn phí · trứng về lại sổ',
  'ถอดการ์ดออกจากสัตว์เลี้ยง? เสีย {a} G — การ์ดกลับเข้าคลัง\n(เก็บเข้าไข่ = การ์ดคืนทั้งหมดฟรี)':'Gỡ thẻ khỏi thú cưng? Tốn {a} G — thẻ về kho\n(thu về trứng = hoàn toàn bộ thẻ miễn phí)',
  '🎴 เลือกการ์ดเสียบสัตว์เลี้ยง':'🎴 Chọn thẻ khảm cho thú cưng',
  'เสียบถาวร (ถอดเสีย {a} G · เก็บเข้าไข่คืนฟรี) · stat มีผลกับผู้เล่นเหมือนการ์ดในโมดูล':'Khảm vĩnh viễn (gỡ tốn {a} G · thu về trứng hoàn miễn phí) · chỉ số áp dụng cho bạn như thẻ trong Module',
  'ดำเนินการไม่สำเร็จ':'Thao tác thất bại', 'เชื่อมต่อไม่ได้ ลองใหม่อีกครั้ง':'Không kết nối được — thử lại nhé',
  // ── คู่มือไอเทม (ITEM_HELP) ──
  'ยาฟื้นฟู T1-T6':'Thuốc hồi phục T1-T6', 'เปิด/ปิดรายระดับ':'Bật/tắt từng bậc', 'AUTO และ Threshold':'AUTO và ngưỡng HP',
  'สมุนไพร (Herb)':'Thảo dược', 'ของสะสม (Treasures)':'Bảo vật', 'ชิ้นส่วนฮาร์ดแวร์ / STAT / ยานบิน / อาวุธ':'Linh kiện Hardware / STAT / phi thuyền / vũ khí',
  'มี 6 ระดับ: ⚪T1+30 🟢T2+60 🔵T3+100 🟣T4+150 🟡T5+250 🔴T6+400 HP\nระบบใช้ T สูงสุดที่เปิดไว้และมีสต็อกก่อนเสมอ\nปลดล็อค T2-T6 ตามเลเวลยานบิน':'6 bậc: ⚪T1+30 🟢T2+60 🔵T3+100 🟣T4+150 🟡T5+250 🔴T6+400 HP\nLuôn ưu tiên dùng T cao nhất đang bật và còn hàng\nT2-T6 mở khóa theo cấp phi thuyền',
  'กดปุ่มเปิด/ปิดแต่ละ T แยกกัน ยาที่ปิดจะไม่ถูกใช้อัตโนมัติ\nมีประโยชน์เมื่อต้องการเก็บ T สูงไว้ใช้เฉพาะบอส':'Bật/tắt từng T riêng — thuốc bị tắt sẽ không tự dùng\nTiện khi muốn để dành T cao đánh Boss',
  'เปิด AUTO → กินยาอัตโนมัติเมื่อ HP ต่ำกว่า threshold ที่ตั้ง (30-90%)\nHP < 30% จะกินยาเสมอแม้ปิด AUTO\nปรับ threshold จาก dropdown':'Bật AUTO → tự uống thuốc khi HP dưới ngưỡng đã đặt (30-90%)\nHP < 30% luôn uống kể cả tắt AUTO\nChỉnh ngưỡng bằng dropdown',
  'วัตถุดิบผลิตยา เก็บได้จากแผนที่หรือดรอปมอน\nต้นทุน: T1×5 T2×10 T3×15 T4×20 T5×25 T6×30 สมุนไพร/ขวด':'Nguyên liệu chế thuốc, nhặt trên bản đồ hoặc rơi từ quái\nChi phí: T1×5 T2×10 T3×15 T4×20 T5×25 T6×30 thảo dược/bình',
  'ดรอปจากมอน มีระดับสี white→green→blue→purple→gold→red\nยิ่งหายากยิ่งโบนัสสูง รวมของสะสมทุกหมวดไว้ในเมนูไอเทมนี้':'Rơi từ quái, cấp màu white→green→blue→purple→gold→red\nCàng hiếm thưởng càng cao — mọi bộ sưu tập gom trong menu Vật phẩm này',
  'สะสมเพื่อปลดล็อคโบนัสถาวร เช่น HP max / EXP / Gold\nของสะสมทุกหมวดดูรวมกันได้ในเมนูไอเทมนี้':'Sưu tầm để mở thưởng vĩnh viễn như HP max / EXP / Gold\nMọi bộ sưu tập xem chung trong menu Vật phẩm này',
  // ── ชื่อของสะสม: ชิ้นส่วนสเตตัส (STAT_PARTS_MASTER) ──
  'แขนเหล็กโบราณ':'Cánh tay sắt cổ đại', 'รองเท้าพายุ':'Giày bão táp', 'ดวงตาแม่นยำ':'Mắt chuẩn xác',
  'คริสตัลปัญญา':'Pha lê trí tuệ', 'เกราะวิญญาณ':'Giáp linh hồn', 'ใบโคลเวอร์ทอง':'Cỏ ba lá vàng',
  'แขนกลอัลลอย':'Cánh tay máy hợp kim', 'รองเท้าลม':'Giày gió', 'ใบมีดฝึกจิต':'Lưỡi dao luyện tâm',
  'คัมภีร์โบราณ':'Cổ thư', 'เสื้อเกราะเหล็ก':'Áo giáp sắt', 'ดอกซากุระนำโชค':'Hoa anh đào may mắn',
  'ค้อนยักษ์พลังงาน':'Búa khổng lồ năng lượng', 'ขนนกอินทรี':'Lông đại bàng', 'คริสตัลนักธนู':'Pha lê xạ thủ',
  'ห้องทดลองจิ๋ว':'Phòng thí nghiệm mini', 'กำแพงปราสาท':'Tường thành', 'พระจันทร์มงคล':'Trăng cát tường',
  'ตราสามง่ามไทเทน':'Ấn đinh ba Titan', 'สายฟ้าจับขา':'Tia chớp bám chân', 'ตาสามตาทอง':'Thiên nhãn vàng',
  'หลอดไฟแห่งปัญญา':'Bóng đèn trí tuệ', 'แก้วพลังชีวิต':'Ngọc sinh lực', 'ดาวนำโชคทอง':'Sao may mắn vàng',
  'ใบดาบปีศาจ':'Lưỡi kiếm ác quỷ', 'ลมมรสุมปีศาจ':'Gió mùa ác quỷ', 'วังวนมิติ':'Xoáy không gian',
  'แสงดาวแห่งความรู้':'Ánh sao tri thức', 'มงกุฎอมตะ':'Vương miện bất tử', 'สายรุ้งมหามงคล':'Cầu vồng đại cát',
  'ดาบปีศาจเลือด':'Kiếm quỷ huyết', 'ลมวิญญาณ':'Gió linh hồn', 'ตาเพชรมรณะ':'Mắt kim cương tử thần',
  'เปลวเพลิงปัญญา':'Ngọn lửa trí tuệ', 'หัวใจอมตะ':'Trái tim bất tử', 'ลูกเต๋าโชคชะตา':'Xúc xắc định mệnh',
  // ── ชื่อ+คำอธิบาย: ชิ้นส่วนยานบิน (HOUSE_PARTS_MASTER) ──
  'ท่อนไม้มหัศจรรย์':'Khúc gỗ kỳ diệu', 'ชิ้นส่วนสายพาน':'Linh kiện băng chuyền', 'แม่พิมพ์พิเศษ':'Khuôn đúc đặc biệt',
  'กล้องสำรวจระยะ':'Ống kính trinh sát', 'ระเบิดพลังงาน':'Bom năng lượng', 'จานรับสัญญาณ':'Chảo thu tín hiệu',
  'แรงระเบิดแดง':'Khối nổ đỏ', 'หอสัญญาณพลังงาน':'Tháp tín hiệu năng lượng', 'คลื่นพลังทำลาย':'Sóng hủy diệt',
  'โมดูลจักรวาล':'Module vũ trụ', 'แกนนิวเคลียร์':'Lõi hạt nhân', 'คอร์กาแลคซี่':'Lõi thiên hà', 'ดาวตกมิติ':'Sao băng không gian',
  'ไม้ให้พลังงาน +2/ชิ้น':'Gỗ cho +2 năng lượng/khúc',
  '5% โอกาสได้มีดสั้น +2/รอบ':'5% cơ hội +2 dao găm/chu kỳ', '5% โอกาสได้มีดยาว +1/รอบ':'5% cơ hội +1 dao dài/chu kỳ',
  'ระยะ Premium Titan Beam ยานบิน +0.33m':'Tầm Premium Titan Beam phi thuyền +0.33m',
  'ระยะ Premium Titan Beam ยานบิน +0.67m':'Tầm Premium Titan Beam phi thuyền +0.67m',
  'ระยะ Premium Titan Beam ยานบิน +1.0m':'Tầm Premium Titan Beam phi thuyền +1.0m',
  'ระยะ Premium Titan Beam ยานบิน +1.33m':'Tầm Premium Titan Beam phi thuyền +1.33m',
  'ระยะ Premium Titan Beam ยานบิน +1.67m':'Tầm Premium Titan Beam phi thuyền +1.67m',
  'ระยะ Premium Titan Beam ยานบิน +2.0m':'Tầm Premium Titan Beam phi thuyền +2.0m',
  'DMG Premium Titan Beam ยานบิน +10':'DMG Premium Titan Beam phi thuyền +10',
  'DMG Premium Titan Beam ยานบิน +15':'DMG Premium Titan Beam phi thuyền +15',
  'DMG Premium Titan Beam ยานบิน +20':'DMG Premium Titan Beam phi thuyền +20',
  'DMG Premium Titan Beam ยานบิน +25':'DMG Premium Titan Beam phi thuyền +25',
  // ── ชื่อ+คำอธิบาย: ชิ้นส่วนอาวุธ (WEAPON_PARTS_MASTER) ──
  'กล้องซูมมีดสั้น':'Ống zoom dao găm', 'เลนส์สีเขียว':'Thấu kính xanh lá', 'ปริซึมฟ้า':'Lăng kính xanh dương',
  'คริสตัลม่วง':'Pha lê tím', 'แกนทองคำ':'Lõi vàng ròng', 'แกนดาวแดง':'Lõi sao đỏ',
  'สโคปซุ่มยิง':'Ống ngắm bắn tỉa', 'จานสัญญาณสีเขียว':'Chảo tín hiệu xanh lá', 'เลนส์ควอนตัมฟ้า':'Thấu kính lượng tử xanh dương',
  'ออปติกม่วง':'Kính quang học tím', 'สโคปทองคำ':'Ống ngắm vàng ròng', 'สโคปดาวแดง':'Ống ngắm sao đỏ', 'ซองมีดขยาย':'Bao dao mở rộng',
  'ระยะยิง มีดสั้น +0.33m':'Tầm bắn dao găm +0.33m', 'ระยะยิง มีดสั้น +0.67m':'Tầm bắn dao găm +0.67m', 'ระยะยิง มีดสั้น +1.0m':'Tầm bắn dao găm +1.0m',
  'ระยะยิง มีดยาว +0.33m':'Tầm bắn dao dài +0.33m', 'ระยะยิง มีดยาว +0.67m':'Tầm bắn dao dài +0.67m', 'ระยะยิง มีดยาว +1.0m':'Tầm bắn dao dài +1.0m',
  'ความจุกระสุน +5':'Sức chứa đạn +5',
  // ── ชื่อ+คำอธิบาย: ชิ้นส่วนไททัน (HARDWARE_MASTER) ──
  'ขดลวดพลาสม่า':'Cuộn dây plasma', 'แกนไจโรสโคป':'Lõi con quay hồi chuyển', 'คอร์ควอนตัม':'Lõi lượng tử',
  'คอร์นิวเคลียร์':'Lõi hạt nhân', 'แกนดาร์กแมทเทอร์':'Lõi vật chất tối', 'คอร์ดาร์กแมทเทอร์แดง':'Lõi vật chất tối đỏ',
  'ชิปเพิ่มแรง':'Chip tăng lực', 'ชิปโจมตีสีเขียว':'Chip tấn công xanh lá', 'ชิปโจมตีฟ้า':'Chip tấn công xanh dương',
  'ชิปโจมตีม่วง':'Chip tấn công tím', 'ชิปโจมตีทอง':'Chip tấn công vàng', 'ชิปโจมตีแดง':'Chip tấn công đỏ',
  'ใบมีดไทเทเนียม':'Lưỡi dao titan', 'แบตเตอรี่จิ๋ว':'Pin mini', 'แบตเตอรี่ไฮเพอร์':'Pin hyper',
  'แบตเตอรี่ฟ้า':'Pin xanh dương', 'แบตเตอรี่ม่วง':'Pin tím', 'แบตเตอรี่ทอง':'Pin vàng', 'แบตเตอรี่แดง':'Pin đỏ',
  'ระยะ Premium Titan Beam +0.33m':'Tầm Premium Titan Beam +0.33m', 'ระยะ Premium Titan Beam +0.67m':'Tầm Premium Titan Beam +0.67m',
  'ระยะ Premium Titan Beam +1.0m':'Tầm Premium Titan Beam +1.0m', 'ระยะ Premium Titan Beam +1.33m':'Tầm Premium Titan Beam +1.33m',
  'ธนูไททัน (ARM) ATK +10':'Cung Titan (ARM) ATK +10', 'ธนูไททัน (ARM) ATK +15':'Cung Titan (ARM) ATK +15',
  'ธนูไททัน (ARM) ATK +20':'Cung Titan (ARM) ATK +20', 'ธนูไททัน (ARM) ATK +25':'Cung Titan (ARM) ATK +25',
  'ธนูไททัน (ARM) ATK +30':'Cung Titan (ARM) ATK +30', 'ธนูไททัน (ARM) ATK +35':'Cung Titan (ARM) ATK +35',
  'ขวาน ATK +10':'Rìu ATK +10',
  // ── ชื่อ+คำอธิบาย: ของล้ำค่า (TREASURE_MASTER) ──
  'แม่เหล็กแร่เหล็ก':'Nam châm quặng sắt', 'ใบไม้มหัศจรรย์':'Lá cây kỳ diệu', 'แบตเตอรี่โบราณ':'Pin cổ đại',
  'คอร์พลังงานสีเขียว':'Lõi năng lượng xanh lá', 'คอร์พลังงานฟ้า':'Lõi năng lượng xanh dương', 'คอร์พลังงานม่วง':'Lõi năng lượng tím',
  'คอร์พลังงานทอง':'Lõi năng lượng vàng', 'คอร์พลังงานแดง':'Lõi năng lượng đỏ', 'ต้นไม้โบราณ':'Cây cổ thụ',
  'แร่ทองแดงวิเศษ':'Quặng đồng phép thuật', 'หินศักดิ์สิทธิ์':'Đá thiêng', 'รองเท้าสายฟ้า':'Giày tia chớp',
  'รองเท้าพลังสีเขียว':'Giày sức mạnh xanh lá', 'รองเท้าพลังฟ้า':'Giày sức mạnh xanh dương', 'รองเท้าพลังม่วง':'Giày sức mạnh tím',
  'รองเท้าพลังทอง':'Giày sức mạnh vàng', 'รองเท้าพลังแดง':'Giày sức mạnh đỏ',
  'เหล็กดรอป +1 เสมอทุกครั้ง':'Luôn +1 sắt mỗi lần rơi', 'ใบไม้ดรอป +1 เสมอทุกครั้ง':'Luôn +1 lá mỗi lần rơi',
  'ไม้ดรอป +1 เสมอทุกครั้ง':'Luôn +1 gỗ mỗi lần rơi', 'ทองแดงดรอป +1 เสมอทุกครั้ง':'Luôn +1 đồng mỗi lần rơi',
  'หินดรอป +1 เสมอทุกครั้ง':'Luôn +1 đá mỗi lần rơi',
  'EXP รับได้เพิ่ม +3%':'EXP nhận thêm +3%', 'ความเร็วในการเดิน +25%':'Tốc độ di chuyển +25%',
  // ── ผู้ติดตาม/ยานบิน (renderRobot/renderHouse) ──
  // ── แผงผู้ติดตาม (renderRobot + cat/drone/pet panels) ──
  'ผู้ติดตาม เดินตามและโจมตีมอนอัตโนมัติ':'Đồng hành đi theo và tự động đánh quái',
  '🐾 คู่หูวิ่งตาม':'🐾 Bạn đồng hành', '✓ สวมอยู่':'✓ Đang dùng',
  '🐱 กำลังวิ่ง...':'🐱 Đang chạy...', '⏳ {a} นาที':'⏳ {a} phút', '✅ พร้อม':'✅ Sẵn sàng',
  '✅ ใช้งาน':'✅ Hoạt động', '⏸ ปิด':'⏸ Tắt',
  'เนโกะ Lv.{a}':'Neko Lv.{a}', 'แบก {a} นัด · ยา 5 ขวด (มีดสั้น+ยาว)':'Mang {a} viên đạn · 5 bình thuốc (dao găm+dài)',
  'ส่งมีดสั้น+ยาถึงตัว ไม่ต้องวาร์ปยานบิน':'Giao dao găm+thuốc tận nơi, khỏi dịch chuyển về phi thuyền',
  '🔓 ซื้อ Premium 49P / 10 วัน':'🔓 Mua Premium 49P / 10 ngày', '🔓 ซื้อ Premium 39P / 10 วัน':'🔓 Mua Premium 39P / 10 ngày',
  '🚁 กำลังบิน...':'🚁 Đang bay...', '⏳ Cooldown {a} นาที':'⏳ Cooldown {a} phút',
  'แบก {a} นัด · {b} ขวด':'Mang {a} viên · {b} bình', 'หมด {a} วัน':'Hết hạn sau {a} ngày',
  '🤖 ไททัน Lv.{a}/100':'🤖 Titan Lv.{a}/100',
  '⛔ Disabled — กำลังฟื้น (ต้องถึง 30%)':'⛔ Disabled — đang hồi (cần đủ 30%)',
  '⚡ {a}/{b} · ขวาน -10 · ARM/Rail -5 · recover +{c}/s':'⚡ {a}/{b} · Rìu -10 · ARM/Rail -5 · recover +{c}/s',
  'ขวาน':'Rìu', 'ATK {a} | ระยะ {b}m | ไม่ใช้มีดสั้น':'ATK {a} | Tầm {b}m | không tốn dao găm',
  'ขวานฟันโดน → มอนมึน {a}s (ยกเว้น MVP) · -15⚡':'Rìu chém trúng → quái choáng {a}s (trừ MVP) · -15⚡',
  'ธนูไททัน (ARM)':'Cung Titan (ARM)',
  '⚡ ช็อต {a}s (+0.2s/tier) · ไม่ทำ DMG | ระยะ {b}m':'⚡ Sốc điện {a}s (+0.2s/tier) · không gây DMG | Tầm {b}m',
  '✅ {a}วัน':'✅ {a} ngày', 'ATK {a} | ระยะ {b}m | ใช้ -5⚡/นัด':'ATK {a} | Tầm {b}m | tốn -5⚡/phát',
  'ATK {a} | ระยะ {b}m':'ATK {a} | Tầm {b}m',
  // ── แผงยานบิน (renderHouse) ──
  '🛸 ยานบินจะถูกสร้างอัตโนมัติ — หรือกดปุ่มด้านล่างเพื่อสร้างทันที':'🛸 Phi thuyền sẽ tự được xây — hoặc bấm nút bên dưới để xây ngay',
  '🛸 สร้างยานบินเดี๋ยวนี้':'🛸 Xây phi thuyền ngay',
  '📦 คลัง:':'📦 Kho:', '🛸 ยาน Orion Lv.{a}/100':'🛸 Tàu Orion Lv.{a}/100',
  'ยานสูงสุด Lv.{a} ที่ผู้เล่น Lv.{b} — อัพเลเวลผู้เล่นก่อน':'Tàu tối đa Lv.{a} khi người chơi Lv.{b} — nâng cấp nhân vật trước',
  'คลัง {a}/{b} นัด · ⚙️{c} 🟫{d} ⚡{e}':'Kho {a}/{b} viên · ⚙️{c} 🟫{d} ⚡{e}',
  'คลัง {a}/{b} ขวด · 🌿×{c}/ขวด':'Kho {a}/{b} bình · 🌿×{c}/bình',
  'เต็ม':'Đầy', 'ปิดผลิต':'Ngừng sản xuất', 'คลังเต็ม':'Kho đầy', 'รอบล่าสุด: {a}':'Chu kỳ gần nhất: {a}',
  '🔒 ปลดล็อกยาน Lv.20':'🔒 Mở khóa ở tàu Lv.20',
  'ยิงสนับสนุน AOE อัตโนมัติ — อัพยาน Orion ถึง Lv.20 เพื่อเปิดใช้งาน (อีก {a} Lv.)':'Bắn yểm trợ AOE tự động — nâng tàu Orion lên Lv.20 để kích hoạt (còn {a} Lv.)',
  'ยิงสนับสนุนอัตโนมัติ · ระยะ 300m · CD 15s · ใช้ 20⚡/นัด':'Bắn yểm trợ tự động · tầm 300m · CD 15s · tốn 20⚡/phát',
  '🔒 ต้องมี Premium Orion Gun':'🔒 Cần Premium Orion Gun',
  'ปืนกลหนัก AOE ยิงชุดละ 3 นัดติด · DMG 1.25× Rail Gun · CD 5s — ปลดล็อกในร้าน Premium (10 วัน)':'Sung may AOE hang nang, loat 3 · DMG 1.25x Rail Gun · CD 5s — mo khoa o cua hang Premium (10 ngay)',
  'DMG {a}/ชุด · ⏳ {b} วัน':'DMG {a}/loạt · ⏳ {b} ngày',
  'ปืนกลหนัก AOE — ยิงชุดละ 3 นัดติด · ระยะ 300m · AOE {a}m · CD 5s · 5⚡/ชุด':'Sung may AOE hang nang — loat 3 vien · tam 300m · AOE {a}m · CD 5s · 5⚡/loat',
  '🔥 เผาไม้':'🔥 Đốt gỗ', '⚡/เผา':'⚡/lần đốt', 'ใช้ 🪵{a}/เผา':'Tốn 🪵{a}/lần đốt', 'ปิดอยู่':'Đang tắt',
  '🛸 ยาน +☀️':'🛸 Tàu +☀️', '/นาที':'/phút', 'ยาน {a}':'Tàu {a}',
  '⚡ พลังงานเหลือ/นาที':'⚡ Năng lượng ròng/phút', 'ผลิต +{a}':'Sản xuất +{a}',
  ' · กระสุน/ยา −{a}':' · đạn/thuốc −{a}', ' · เหมือง −{a}':' · mỏ −{a}',
  'หักเฉพาะ tier ที่กำลังผลิต (คลังยังไม่เต็ม) — คลังเต็มแล้วหยุดกิน พลังงานจะไต่ขึ้นเต็ม':'Chỉ trừ các tier đang sản xuất (kho chưa đầy) — kho đầy sẽ ngừng tiêu hao, năng lượng leo lại lên đầy',
  '🔥 เผาไม้ผลิตพลังงาน':'🔥 Đốt gỗ tạo năng lượng',
  'เปิด/ปิด การเผาไม้ผลิตพลังงาน':'Bật/tắt đốt gỗ tạo năng lượng', 'เปิด/ปิด เผาไม้':'Bật/tắt đốt gỗ',
  '🔒 ต้องการยานบิน Lv.{a} (ปัจจุบัน Lv.{b})':'🔒 Cần phi thuyền Lv.{a} (hiện tại Lv.{b})',
  '⚡ +{a}/นาที (passive)':'⚡ +{a}/phút (passive)', 'ยังไม่ได้สร้าง':'Chưa xây',
  '🔒 ยานบิน Lv.{a} ปลดล็อค':'🔒 Mở khóa ở phi thuyền Lv.{a}', 'Lv.1 (สร้าง)':'Lv.1 (xây)',
  'Solar สูงสุด = ยานบิน Lv.{a} (อัพยานบินก่อน)':'Solar tối đa = phi thuyền Lv.{a} (nâng phi thuyền trước)',
  'ใช้วัตถุดิบประมาณ ⚙️{a} 🟫{b}/นาที':'Tiêu tốn khoảng ⚙️{a} 🟫{b}/phút',
  'ลูกธนูไททัน':'Tên Titan', '/นาที · 🌿 ตาม tier':'/phút · 🌿 theo tier',
  '⛏️ เหมืองแร่':'⛏️ Mỏ khoáng',
  'กิน ⚡1+💰1/ชิ้น · ผลิต Lv×8 ชิ้น/นาที · แร่เข้าคลัง':'Tốn ⚡1+💰1/viên · sản xuất Lv×8 viên/phút · quặng vào kho',
  '⏸ เหมือง 4 · {a} Lv.{b} — Premium Miner หมดอายุ':'⏸ Mỏ 4 · {a} Lv.{b} — Premium Miner hết hạn',
  'ต่ออายุเพื่อผลิตต่อ':'Gia hạn để sản xuất tiếp',
  '🔒 เหมือง 4 — ปลดที่ยานบิน Lv.{a}':'🔒 Mỏ 4 — mở ở phi thuyền Lv.{a}',
  '🔒 เหมือง 4 — ต้องมี Premium Miner ⛏️':'🔒 Mỏ 4 — cần Premium Miner ⛏️',
  '🔒 เหมือง {a} — {b}':'🔒 Mỏ {a} — {b}', 'เร็วๆ นี้':'Sắp ra mắt', 'ปลดที่ยานบิน Lv.{a}':'mở ở phi thuyền Lv.{a}',
  '⛏️ เหมือง {a} · ยังไม่สร้าง':'⛏️ Mỏ {a} · chưa xây', '🔨 สร้างเหมือง (Lv.1)':'🔨 Xây mỏ (Lv.1)',
  '▶ เปิด':'▶ Bật', '⏸ พัก':'⏸ Nghỉ', '⛏️ เหมือง {a}':'⛏️ Mỏ {a}', 'พัก':'Nghỉ',
  '⛔ ตันที่ Lv ยานบิน ({a}) — อัพยานบินก่อน':'⛔ Kịch trần Lv phi thuyền ({a}) — nâng phi thuyền trước',
  'วัสดุไม่พอ':'Không đủ nguyên liệu', 'สร้างยานบินไม่ได้':'Không thể xây phi thuyền', 'ไม่พอ Gold':'Không đủ Gold',
  // ── คู่มือไททัน (ROBOT_HELP) ──
  'เดินตามผู้เล่น':'Đi theo người chơi',
  'ไททันจะเดินตามผู้เล่นตลอดเวลา และโจมตีมอนสเตอร์ที่อยู่ในระยะโดยอัตโนมัติ':'Titan luôn đi theo bạn và tự động tấn công quái trong tầm',
  'ขวานไททัน (ระยะประชิด)':'Rìu Titan (cận chiến)',
  'โจมตีมอนในระยะใกล้ ยิ่งอัพเกรด ATK ยิ่งสูง อัพได้ที่แถบ ARM ในหน้านี้':'Đánh quái tầm gần; càng nâng cấp ATK càng cao — nâng ở mục ARM trong trang này',
  'ธนูไททัน ARM (ดาเมจ + ดึง)':'Cung Titan ARM (sát thương + kéo)',
  'ช็อตมอนให้หยุดนิ่ง (ไม่ทำ DMG) · ยกเว้น MVP · ไม่ช็อตซ้ำตัวที่กำลังช็อตอยู่ · ใช้ลูกธนูไททัน 1 นัด/ช็อต\nระยะเวลาช็อต = 0.1s×Lv + 0.2s×(tier−1) · หากมีดสั้น < 5 และเปิดเติมอัตโนมัติ ไททันจะวาร์ปกลับยานบินเพื่อเติม':'Sốc điện làm quái đứng yên (không gây DMG) · trừ MVP · không sốc lại con đang bị sốc · tốn 1 tên Titan/lần sốc\nThời gian sốc = 0.1s×Lv + 0.2s×(tier−1) · nếu dao găm < 5 và bật tự nạp, Titan sẽ dịch chuyển về phi thuyền để nạp',
  'Premium Titan Beam (ใช้พลังงาน)':'Premium Titan Beam (tốn năng lượng)',
  'ยิงรังสีพลังสูง ดีเลย์ชาร์จก่อนยิง\nกินพลังงานไททันต่อการยิง หากพลังงานหมด ไททันจะวาร์ปกลับยานบินเพื่อชาร์จ\nยานบินต้องมีพลังงานสำรองก่อน':'Bắn tia năng lượng cao, có độ trễ sạc trước mỗi phát\nMỗi phát tốn năng lượng Titan; hết năng lượng Titan sẽ dịch chuyển về phi thuyền để sạc\nPhi thuyền phải có năng lượng dự trữ trước',
  'พลังงานไททัน':'Năng lượng Titan',
  'ไททันมีแถบพลังงานของตัวเอง เมื่อหมดจะวาร์ปกลับยานบินดูดพลังงานจากคลังยานบิน\nพลังงานยานบินผลิตได้ที่ Lv.3 ขึ้นไป':'Titan có thanh năng lượng riêng; khi cạn sẽ dịch chuyển về phi thuyền hút năng lượng từ kho\nPhi thuyền sản xuất năng lượng từ Lv.3 trở lên',
  'วาร์ปกลับยานบิน':'Dịch chuyển về phi thuyền',
  'ไททันวาร์ปกลับยานบินอัตโนมัติเมื่อ: ลูกธนูไททัน < 5 (เปิดออโต้) หรือพลังงานหมด\nหลังเติมแล้วจะวาร์ปกลับมาหาผู้เล่น':'Titan tự dịch chuyển về phi thuyền khi: tên Titan < 5 (bật auto) hoặc cạn năng lượng\nNạp xong sẽ dịch chuyển quay lại chỗ bạn',
  'อัพเกรดไททัน':'Nâng cấp Titan',
  'อัพ Lv. ไททัน: เพิ่ม HP และพลังงานสูงสุด\nอัพ ธนูไททัน (ARM) / ขวาน: เพิ่ม ATK\nอัพ Premium Titan Beam: เพิ่มพลังและลดดีเลย์':'Nâng Lv. Titan: tăng HP và năng lượng tối đa\nNâng cung Titan (ARM) / rìu: tăng ATK\nNâng Premium Titan Beam: mạnh hơn, ít trễ hơn',
  'ชิ้นส่วนไททัน (HARDWARE)':'Linh kiện Titan (HARDWARE)',
  'ดรอปจากมอนสเตอร์ สะสมครบเพื่อปลดล็อคโบนัส\nดูและสะสมได้ในเมนู 🎒 ไอเทม (รวมของสะสมทุกหมวด)':'Rơi từ quái; sưu tầm đủ bộ để mở thưởng\nXem và sưu tầm trong menu 🎒 Vật phẩm (gom mọi bộ sưu tập)',
  // ── คู่มือยานบิน (HOUSE_HELP) ──
  'ยานบิน — ฐานทัพหลัก':'Phi thuyền — căn cứ chính',
  'วางยานบินได้ 1 หลัง อัพเกรดเพิ่มฟีเจอร์ตามระดับ\nใช้ไม้ + หินเป็นวัตถุดิบ (หิน = ไม้ × 4 เสมอ)\nดูวัสดุคลังได้ที่แถบ 📦 คลัง บนสุดของหน้านี้':'Đặt được 1 phi thuyền; nâng cấp thêm tính năng theo cấp\nDùng gỗ + đá làm nguyên liệu (đá = gỗ × 4 luôn)\nXem nguyên liệu trong kho ở thanh 📦 Kho đầu trang này',
  'ผลิตกระสุน T1-T6 (Lv.1+)':'Sản xuất đạn T1-T6 (Lv.1+)',
  'ยานบินผลิตกระสุนของ มีดสั้น / มีดยาว / ธนูไททัน (ARM) อัตโนมัติ\nมี 6 ระดับ เปิด/ปิดรายระดับได้\n⚙️เหล็ก 1/2/5/8/12/15 (T1-T6) + ⚡1/นัด (ทุก T)\n🟫ทองแดง = เหล็ก × มีดสั้น ×1.0 · ธนูไททัน ×1.25 · มีดยาว ×1.5':'Phi thuyền tự sản xuất đạn cho Dao găm / Dao dài / Cung Titan (ARM)\n6 tier, bật/tắt từng tier riêng\n⚙️Sắt 1/2/5/8/12/15 (T1-T6) + ⚡1/viên (mọi T)\n🟫Đồng = sắt × Dao găm ×1.0 · Cung Titan ×1.25 · Dao dài ×1.5',
  'ผลิตยา T1-T6 (Lv.1+)':'Sản xuất thuốc T1-T6 (Lv.1+)',
  'ผลิตยาได้ 6 ระดับ เปิด/ปิดแต่ละ T ได้อิสระ\nต้นทุน: 🌿×5/10/15/20/25/30 ต่อขวด (T1-T6) + ⚡3/ขวด\nยาเก็บในคลังยานบิน หยิบอัตโนมัติเมื่อวาร์ปกลับ':'Sản xuất 6 tier thuốc, bật/tắt từng T độc lập\nChi phí: 🌿×5/10/15/20/25/30 mỗi bình (T1-T6) + ⚡3/bình\nThuốc lưu trên phi thuyền, tự nhặt khi dịch chuyển về',
  'พลังงานยานบิน':'Năng lượng phi thuyền',
  'ได้จาก 3 ทาง:\n🛸 ยาน Orion: passive +20⚡/นาที ต่อ Lv.ยาน (ไม่ต้องมีอะไร)\n🪵 เผาไม้: Lv.1 = 88⚡/เผา (×4) ยิ่ง Lv.สูงยิ่งได้มาก\n☀️ Solar Cell: passive ไม่ใช้ไม้ (Lv.1=+27⚡/นาที, stack กัน)':'Đến từ 3 nguồn:\n🛸 Tàu Orion: passive +20⚡/phút mỗi Lv. tàu (không cần gì)\n🪵 Đốt gỗ: Lv.1 = 88⚡/lần đốt (×4), Lv. càng cao càng nhiều\n☀️ Solar Cell: passive không tốn gỗ (Lv.1=+27⚡/phút, cộng dồn)',
  'ผลิต ⚡ ทุกนาทีโดยไม่ต้องใช้ไม้ stack กับการเผาไม้\nสูตร: Lv.N → +N×27 ⚡/นาที':'Tạo ⚡ mỗi phút không cần gỗ, cộng dồn với đốt gỗ\nCông thức: Lv.N → +N×27 ⚡/phút',
  'Premium Titan Beam ยานบิน (Lv.4+)':'Premium Titan Beam phi thuyền (Lv.4+)',
  'ป้องกันมอนอัตโนมัติรอบๆ ยานบิน ATK = (80+(Lv-1)×30)×1.2\nระยะยิงพื้นฐาน 60m (เท่า Premium Titan Beam) อัพเกรดด้วย 🪨หิน + 💰Gold':'Tự phòng thủ quái quanh phi thuyền, ATK = (80+(Lv-1)×30)×1.2\nTầm bắn cơ bản 60m (bằng Premium Titan Beam), nâng cấp bằng 🪨đá + 💰Gold',
  'กดปุ่ม 🛸 ข้างปุ่มซูม หรือให้ระบบออโต้วาร์ปเมื่อต้องการเติมของ\nเมื่อกลับถึงยานบินจะรับมีดสั้น/ยา/พลังงานทันที':'Bấm nút 🛸 cạnh nút zoom, hoặc để game tự dịch chuyển khi cần tiếp tế\nVề đến phi thuyền sẽ nhận ngay dao găm/thuốc/năng lượng',
  'ชิ้นส่วนยานบิน':'Linh kiện phi thuyền',
  'ดรอปจากมอน สะสมเพื่อโบนัส เช่น ผลิตกระสุนเพิ่ม / เพิ่มระยะ Premium Titan Beam\nดูและสะสมได้ในเมนู 🎒 ไอเทม (รวมของสะสมทุกหมวด)':'Rơi từ quái; sưu tầm nhận thưởng như sản xuất thêm đạn / tăng tầm Premium Titan Beam\nXem và sưu tầm trong menu 🎒 Vật phẩm (gom mọi bộ sưu tập)',
  // ── ตลาด/อันดับ/Premium (renderMarket/rank/renderPremium) ──
  // ── อันดับผู้เล่น (renderRank) ──
  'กำลังโหลด...':'Đang tải...', 'โหลดไม่ได้':'Không tải được', 'ยังไม่มีการกำจัด MVP':'Chưa có lượt hạ MVP nào',
  '— ไม่มี drop':'— không có drop', '{a} การกำจัดล่าสุด':'{a} lượt hạ gần đây', 'อัปเดตทุกครั้งที่เปิด':'Cập nhật mỗi lần mở',
  'มอน':'Quái',
  // ── MVP kill log — เวลา + ป้าย drop ──
  'เมื่อกี้':'vừa xong', '{a} นาทีที่แล้ว':'{a} phút trước', '{a} ชม.ที่แล้ว':'{a} giờ trước', '{a} วันที่แล้ว':'{a} ngày trước',
  '💎เพชรฟ้า +1':'💎Kim cương xanh +1', '🔴เพชรแดง +1':'🔴Kim cương đỏ +1',
  '💎เพชรฟ้า +1!':'💎Kim cương xanh +1', '🔴เพชรแดง +1!':'🔴Kim cương đỏ +1',
  'ไข่ {a}':'Trứng {a}', 'ซ้ำ x{a}':'trùng x{a}',
  'พบของล้ำค่า!':'Bảo vật!', 'ได้อุปกรณ์!':'Trang bị!', 'ได้ HARDWARE!':'HARDWARE!',
  'ได้ของวิเศษ STAT!':'Linh kiện STAT!', 'ได้ชิ้นส่วนยานบิน!':'Linh kiện phi thuyền!', 'ได้ชิ้นส่วนอาวุธ!':'Linh kiện vũ khí!',
  // ── ชื่ออุปกรณ์สวมใส่ 36 ชิ้น (XHRPG_EQUIPMENT ฝั่ง server) ──
  'หมวกเหล็ก':'Mũ sắt', 'หมวกกู้ภัย':'Mũ cứu hộ', 'หมวกนักปราชญ์':'Mũ học giả', 'หมวกพ่อมด':'Mũ pháp sư', 'หมวกสุภาพบุรุษ':'Mũ quý ông', 'มงกุฎราชา':'Vương miện nhà vua',
  'เสื้อผ้าเก่า':'Quần áo cũ', 'ชุดยูโด':'Võ phục judo', 'เสื้อกันกระสุน':'Áo chống đạn', 'เกราะโลหะ':'Giáp kim loại', 'เกราะคอมโพสิต':'Giáp composite', 'เกราะมังกร':'Giáp rồng',
  'ถุงมือผ้า':'Găng tay vải', 'นวมนักมวย':'Găng boxing', 'ถุงมือหนัง':'Găng tay da', 'ถุงมือเหล็ก':'Găng tay sắt', 'ถุงมือไทเทเนียม':'Găng tay titan', 'ถุงมือมังกร':'Găng tay rồng',
  'รองเท้าผ้าใบ':'Giày thể thao', 'รองเท้าหนัง':'Giày da', 'รองเท้านักรบ':'Giày chiến binh', 'บูทหนัก':'Bốt hạng nặng', 'รองเท้าสายลม':'Hài gió',
  'แหวนเหมาะมือ':'Nhẫn vừa tay', 'แหวนเงิน':'Nhẫn bạc', 'แหวนพลังน้ำ':'Nhẫn thủy lực', 'แหวนวังวน':'Nhẫn xoáy nước', 'แหวนไดมอนด์':'Nhẫn kim cương', 'แหวนมังกรทอง':'Nhẫn rồng vàng',
  'จี้คริสตัล':'Mặt dây pha lê', 'จี้ตาปีศาจ':'Mặt dây mắt quỷ', 'จี้เพชร':'Mặt dây kim cương', 'จี้กระจกวิเศษ':'Mặt dây gương thần', 'จี้ดาว':'Mặt dây ngôi sao', 'จี้ดาวแห่งโชค':'Mặt dây sao may mắn',
  // ── รางวัลออฟไลน์ (showOfflineReward/_offDropsGrid/_offPremiumBox) ──
  '{a} ชม {b} นาที':'{a} giờ {b} phút', '{a} นาที':'{a} phút',
  'ไม้':'Gỗ', 'หิน':'Đá', 'เหล็ก':'Sắt', 'ทองแดง':'Đồng', 'สมุนไพร':'Thảo dược',
  'เพชรฟ้า':'Kim cương xanh', 'เพชรแดง':'Kim cương đỏ', 'เพชรเขียว':'Kim cương lục',
  '⚔️ กำจัดมอนสเตอร์ไปทั้งสิ้น':'⚔️ Tổng số quái đã hạ', 'โซน {a}':'Khu {a}', '{a} <b>{b}</b> ตัว':'{a} <b>{b}</b> con',
  'ยินดีต้อนรับกลับ!':'Chào mừng trở lại!', 'ออฟไลน์ไป {a}':'Offline suốt {a}',
  'เยี่ยม! รับแล้ว ✅':'Tuyệt — đã nhận! ✅',
  'รางวัลเข้าตัวละครอัตโนมัติแล้ว — ปิดได้เลย':'Thưởng đã tự vào nhân vật — đóng được rồi',
  'โมดูล':'Module', 'ไข่':'Trứng', 'การ์ดสะสม':'Thẻ sưu tầm', 'ไข่ PET':'Trứng PET',
  '🎁 ของหายาก (โมดูล/การ์ด/ไข่)':'🎁 Đồ hiếm (Module/thẻ/trứng)', ' — {a} ชนิด':' — {a} loại',
  'รอบนี้ยังไม่ได้ 🔧 โมดูล / 🎴 การ์ด / 🥚 ไข่':'Đợt này chưa được 🔧 Module / 🎴 thẻ / 🥚 trứng',
  'แร่':'Quặng', '(รวมอยู่ในรางวัลด้านบนแล้ว ไม่ใช่บวกเพิ่ม)':'(đã gộp trong thưởng phía trên — không cộng thêm)',
  '(โบนัสพิเศษ — บวกเพิ่มจากรางวัลด้านบน ไม่ได้รวมไว้)':'(thưởng đặc biệt — cộng thêm ngoài thưởng phía trên, chưa gộp)',
  // ── โซนฟาร์ม offline (openOfflinePanel) ──
  '⏳ กำลังโหลด...':'⏳ Đang tải...', '❌ โหลดไม่สำเร็จ':'❌ Tải thất bại', '❌ เชื่อมต่อไม่ได้':'❌ Không kết nối được',
  'ฟาร์มออฟไลน์ — เลือกโซน':'Farm offline — chọn khu', '💾 บันทึกโซนฟาร์ม':'💾 Lưu khu farm',
  'ล็อก':'Khóa', 'มอน:':'Quái:', 'ไม่มีโซนในแผนที่นี้':'Bản đồ này không có khu nào',
  'ℹ️ ยังไม่เคยเลือก — ค่าเริ่มต้นคือ <b>ทุ่งกลาง</b> (ติ๊กไว้ให้แล้ว) · เปลี่ยนได้ตามใจ':'ℹ️ Chưa chọn lần nào — mặc định là <b>Cánh đồng trung tâm</b> (đã tích sẵn) · đổi thoải mái',
  '🔓 ปลดถึง Lv.{a}':'🔓 Đã mở đến Lv.{a}',
  'เลือกได้รวมสูงสุด {a} โซน (ทุกแผนที่)':'Chọn tối đa {a} khu (tính mọi bản đồ)',
  'แมพ{a}':'Bản đồ {a}', 'เลือกแล้ว {a}/{b} โซน รวมทุกแผนที่':'Đã chọn {a}/{b} khu trên mọi bản đồ',
  'สะสมรางวัลสูงสุด 8 ชม.':'Tích thưởng tối đa 8 giờ',
  '💎 PREMIUM OFFLINE 24H REWARD — สะสมสูงสุด 24 ชม. + โบนัส 35%':'💎 PREMIUM OFFLINE 24H REWARD — tích tối đa 24 giờ + thưởng 35%',
  '⏳ กำลังบันทึก...':'⏳ Đang lưu...', 'บันทึกไม่สำเร็จ':'Lưu thất bại', 'เชื่อมต่อไม่ได้':'Không kết nối được',
  // ── Premium items (renderPremium/buyPremium) ──
  'รับ EXP เพิ่ม 35% ทุกการเอาชนะมอนสเตอร์':'Nhận thêm 35% EXP mỗi lần hạ quái',
  'ดรอปของหายาก ×2 — การ์ด/ไข่/โมดูล/เพชร/กล่อง/ของ MVP · ออนไลน์+ออฟไลน์ (ไม่รวมแร่/พืช/ยา)':'Rơi đồ hiếm ×2 — thẻ/trứng/mô-đun/ngọc/rương/vật phẩm MVP · online+offline (không gồm quặng/cây/thuốc)',
  'รับ Gold เพิ่ม 35% ทุกการเอาชนะมอนสเตอร์':'Nhận thêm 35% Gold mỗi lần hạ quái',
  'สุ่มได้แร่ 1-3 ชิ้น (ไม้/หิน/เหล็ก/ทองแดง/พืช) ทุกการเอาชนะมอน + ปลดเหมือง #4 ที่ยานบิน':'Ngẫu nhiên 1-3 quặng (gỗ/đá/sắt/đồng/cây) mỗi lần hạ quái + mở Mỏ #4 trên phi thuyền',
  'ส่งมีดสั้น+ยาถึงตัวโดยไม่ต้องวาร์ปกลับยานบิน | อัพเกรดได้ Lv.1-30':'Giao dao găm+thuốc tận nơi khỏi dịch chuyển về phi thuyền | Nâng cấp Lv.1-30',
  'ไททันยิง Premium Titan Beam | ชาร์จ 5s/นัด | อัพเกรดได้ Lv.1-100':'Titan bắn Premium Titan Beam | sạc 5s/phát | Nâng cấp Lv.1-100',
  'ปลดล็อก Auto Cannon ยานบิน — ปืนกลหนัก AOE ยิงชุดละ 3 นัดติด | DMG 1.25× Rail Gun | CD 5s | อัพเกรดได้ Lv.1-100':'Mở khóa Auto Cannon phi thuyền — súng máy hạng nặng đơn mục tiêu, bắn loạt 3 phát | DMG 1.25× Rail Gun | CD 5s | Nâng cấp Lv.1-100',
  'ฟาร์มออฟไลน์สะสมได้สูงสุด 24 ชม. (ปกติ 8 ชม.) + โบนัส +35% EXP/Gold/แร่ 5 ชนิด บวกเพิ่มจากรางวัลออฟไลน์':'Farm offline tích tối đa 24 giờ (thường 8 giờ) + thưởng +35% EXP/Gold/5 loại quặng cộng thêm vào thưởng offline',
  '✅ กำลังใช้งาน':'✅ Đang kích hoạt', 'หมดอายุ {a}':'Hết hạn {a}',
  'เหลือ {a} วัน {b} ชม. {c} นาที':'Còn {a} ngày {b} giờ {c} phút', 'เหลือ {a} ชม. {b} นาที':'Còn {a} giờ {b} phút',
  '+ ต่อเวลา 10 วัน ({a} P)':'+ Gia hạn 10 ngày ({a} P)', 'ซื้อ 10 วัน ({a} P)':'Mua 10 ngày ({a} P)',
  '{a} P / 10 วัน':'{a} P / 10 ngày',
  'ต่อเวลาอีก 10 วัน (หมดอายุเดิม: {a})':'Gia hạn thêm 10 ngày (hạn cũ: {a})', 'เพิ่มเวลา 10 วัน':'Cộng thêm 10 ngày',
  'ใช้ {a} P Point':'Tốn {a} P Point', 'ยืนยัน':'Xác nhận', 'ซื้อไม่สำเร็จ':'Mua thất bại',
  // ── Reset Stat (renderPremium/confirmStatReset) ──
  '✨ ฟรีวันนี้':'✨ Miễn phí hôm nay',
  '🔄 Reset Stat+Skill (ยังไม่ได้ใช้ Stat/Skill)':'🔄 Reset Stat+Skill (chưa dùng Stat/Skill)',
  '🔄 Reset Stat+Skill (ฟรี 1 ครั้ง/วัน)':'🔄 Reset Stat+Skill (miễn phí 1 lần/ngày)',
  'ฟรี 1 ครั้ง/วัน — ครั้งถัดไป 29 P | คืน Stat และ Skill ทั้งหมดกลับเป็น 5':'Miễn phí 1 lần/ngày — lần sau 29 P | Hoàn toàn bộ Stat và Skill về 5',
  '⚠️ ตัวอย่างผลลัพธ์หลัง Reset':'⚠️ Xem trước kết quả sau Reset',
  '→ ทุก Stat กลับเป็น <b>5</b> และได้รับ <b style="color:#dc2626">{a} Stat Points</b> คืน':'→ mọi Stat về <b>5</b> và bạn nhận lại <b style="color:#dc2626">{a} Stat Points</b>',
  '→ Skills ทั้งหมด Reset และได้รับ <b style="color:#dc2626">{a} Skill Points</b> คืน':'→ toàn bộ Skill được Reset và bạn nhận lại <b style="color:#dc2626">{a} Skill Points</b>',
  '✨ ฟรี (ครั้งแรกของวัน)':'✨ Miễn phí (lần đầu trong ngày)', '🅿️ ค่าใช้บริการ 29 P (คงเหลือ {a} P)':'🅿️ Phí dịch vụ 29 P (còn {a} P)',
  'ยืนยัน Reset Stat+Skill?':'Xác nhận Reset Stat+Skill?', 'การกระทำนี้ไม่สามารถย้อนกลับได้':'Hành động này không thể hoàn tác',
  '📋 Stat ปัจจุบันของคุณ':'📋 Stat hiện tại của bạn', 'Stat Points ที่ยังไม่ได้ใช้: <b>{a}</b>':'Stat Points chưa dùng: <b>{a}</b>',
  '✅ หลัง Reset คุณจะได้รับ':'✅ Sau Reset bạn sẽ nhận',
  '• STR / AGI / VIT / DEX / INT / LUK → <b>5</b> ทุกตัว':'• STR / AGI / VIT / DEX / INT / LUK → <b>5</b> tất cả',
  '• Stat Points คืน <b style="font-size:15px;color:#166534">{a} Points</b>':'• Hoàn Stat Points: <b style="font-size:15px;color:#166534">{a} Points</b>',
  '• Skills ทั้งหมด Reset | Skill Points คืน <b style="font-size:15px;color:#166534">{a} Points</b>':'• Toàn bộ Skill Reset | hoàn Skill Points: <b style="font-size:15px;color:#166534">{a} Points</b>',
  '❌ ยกเลิก':'❌ Hủy', '✅ ยืนยัน Reset':'✅ Xác nhận Reset',
  '❌ Reset ผิดพลาด — server ตอบไม่ใช่ JSON (แจ้งแอดมิน)':'❌ Lỗi Reset — server trả về không phải JSON (báo admin)',
  'Reset ไม่สำเร็จ':'Reset thất bại', '❌ Reset ล้มเหลว (HTTP {a}) — แจ้งแอดมิน':'❌ Reset thất bại (HTTP {a}) — báo admin',
  // ── ร้านสกิน (renderPremium skin shops) ──
  'ใช้งาน(ปุ่มสวม)':'Dùng', '✓ ใช้อยู่':'✓ Đang dùng', 'ซื้อ P{a}':'Mua P{a}',
  '(สูงสุด +{a})':'(tối đa +{a})', '🎲 สุ่ม stat +1~{a}':'🎲 Random stat +1~{a}', '🎲 สุ่มใหม่ {a}P':'🎲 Roll lại {a}P',
  '🎨 สกินไททัน':'🎨 Skin Titan', '🗡️ สกินฮีโร่':'🗡️ Skin Hero', '🐾 ผู้ติดตาม (คู่หูวิ่งตาม)':'🐾 Đồng hành (bạn chạy cùng)',
  'ซื้อครั้งเดียว ใช้ได้ตลอด · 🎯 เลือก STAT เอง (STR/AGI/VIT/DEX/INT/LUK) ได้ค่า MAX เต็มเพดาน — มีผลเฉพาะตอนสวม · <b style="color:{c}">ยิ่ง P สูง STAT MAX ยิ่งสูง (+5 ทุก 1000 P)</b> · เลือกใหม่ได้ {a}P':'Mua một lần, dùng mãi mãi · 🎯 tự chọn STAT (STR/AGI/VIT/DEX/INT/LUK) nhận MAX kịch trần — chỉ hiệu lực khi mặc · <b style="color:{c}">P càng cao STAT MAX càng cao (+5 mỗi 1000 P)</b> · chọn lại {a}P',
  'ซื้อครั้งเดียว ใช้ได้ตลอด · 🎯 เลือก STAT เอง ได้ค่า MAX เต็มเพดาน ติดตัว — มีผลเฉพาะตอนสวม · <b style="color:{c}">ยิ่ง P สูง STAT MAX ยิ่งสูง (+5 ทุก 1000 P)</b> · เลือกใหม่ได้ {a}P':'Mua một lần, dùng mãi mãi · 🎯 tự chọn STAT nhận MAX kịch trần — chỉ hiệu lực khi mặc · <b style="color:{c}">P càng cao STAT MAX càng cao (+5 mỗi 1000 P)</b> · chọn lại {a}P',
  'นักรบฝึกหัด':'Chiến binh tập sự', 'ส้มจี๊ด':'Somjeed', 'ฟรี':'Miễn phí', 'ไม่มีโบนัส':'Không có thưởng',
  // ── ชื่อสกิน Premium — sync กับ SKIN_DEFS/HERO_SKIN_DEFS/PET_SKIN_DEFS (+ XHRPG_I18N ฝั่ง PHP) ──
  'มาตี้':'Marty', 'จัสมาท่า':'Jasmatha', 'อามเมออาย':'Ameoai', 'มอนทาน่า':'Montana', 'โคเวล':'Kowel',
  'ดำ':'Đen', 'นาคี':'Naga', 'จี๊ด':'Jeed', 'เงา':'Bóng Đêm', 'ปีกฟ้า':'Cánh Xanh', 'จิ๊บ':'Chíp Chíp',
  'ครีม':'Kem', 'โลโบ':'Lobo', 'แซะ':'Đào Đào', 'ช็อกโก':'Choco', 'แบล็ค':'Mun', 'นุ่น':'Bông', 'หลินฮุ่ย':'Lin Hui',
  'นักรบพเนจร':'Chiến binh lang thang', 'นักรบรับจ้าง':'Lính đánh thuê', 'อัศวิน':'Hiệp sĩ', 'อัศวินเหล็ก':'Hiệp sĩ sắt',
  'อัศวินเหล็กราชา':'Hiệp sĩ sắt hoàng gia', 'ผู้กล้า':'Dũng sĩ', 'ผู้กล้าระดับสูง':'Dũng sĩ tinh nhuệ', 'ผู้กล้าในตำนาน':'Dũng sĩ huyền thoại',
  'P Point คงเหลือ':'Số dư P Point', '📋 ประวัติ':'📋 Lịch sử', '▲ ปิด':'▲ Đóng',
  'ซื้อสะสมได้ — บวกเวลาต่อจากที่เหลืออยู่':'Mua cộng dồn — thời gian cộng tiếp vào phần còn lại',
  'เติมรวม':'Tổng đã nạp', 'ใช้ไปรวม':'Tổng đã tiêu', 'ยังไม่มีประวัติ':'Chưa có lịch sử',
  // ── ซื้อ/รีโรล/สวมสกิน (buySkin/rerollSkin/setSkin + hero/pet) ──
  '🎨 สกิน {a}':'🎨 Skin {a}', '🗡️ สกินฮีโร่ {a}':'🗡️ Skin Hero {a}',
  'ซื้อครั้งเดียว ใช้ได้ตลอด — สวมให้ทันทีหลังซื้อ':'Mua một lần, dùng mãi mãi — mặc ngay sau khi mua',
  'คู่หูวิ่งตาม — ซื้อครั้งเดียว ใช้ได้ตลอด · สวมให้ทันที':'Bạn chạy cùng — mua một lần, dùng mãi mãi · trang bị ngay',
  '🎲 สุ่ม STAT (STR/AGI/VIT/DEX/INT/LUK) <b>ค่า +1~{a}</b> ติดสกิน · สุ่มใหม่ได้ {b}P/ครั้ง':'🎲 Random STAT (STR/AGI/VIT/DEX/INT/LUK) <b>+1~{a}</b> gắn trên skin · roll lại {b}P/lần',
  '🎲 สุ่ม STAT (STR/AGI/VIT/DEX/INT/LUK) <b>ค่า +1~{a}</b> ติดตัว · สุ่มใหม่ได้ {b}P/ครั้ง':'🎲 Random STAT (STR/AGI/VIT/DEX/INT/LUK) <b>+1~{a}</b> gắn trên bạn đồng hành · roll lại {b}P/lần',
  '❌ อ่านผลไม่ได้ (server ตอบผิดรูปแบบ)':'❌ Không đọc được kết quả (server trả về sai định dạng)',
  '🎨 ได้สกิน {a} แล้ว — สวมให้ทันที!':'🎨 Đã nhận skin {a} — mặc ngay!',
  '🗡️ ได้สกินฮีโร่ {a} แล้ว — สวมให้ทันที!':'🗡️ Đã nhận skin Hero {a} — mặc ngay!',
  '🐾 รับเลี้ยง {a} แล้ว!':'🐾 Đã nhận nuôi {a}!',
  'ซื้อสกินไม่สำเร็จ':'Mua skin thất bại', 'รับเลี้ยงไม่สำเร็จ':'Nhận nuôi thất bại',
  '❌ ซื้อสกินไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Mua skin thất bại (không kết nối được server)',
  '❌ ซื้อสกินฮีโร่ไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Mua skin Hero thất bại (không kết nối được server)',
  '❌ รับเลี้ยงไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Nhận nuôi thất bại (không kết nối được server)',
  'กำลังสุ่ม...':'Đang roll...', '✨ ระดับตำนาน!':'✨ Cấp huyền thoại!',
  '🎲 สุ่ม STAT ใหม่ — {a}':'🎲 Roll lại STAT — {a}',
  'ของเดิม {a} <b style="color:#dc2626">จะหายถาวร</b>':'{a} hiện tại <b style="color:#dc2626">sẽ mất vĩnh viễn</b>',
  'สุ่มใหม่ทั้ง STAT และค่า (+1~{a}) — อาจได้เท่าเดิมก็ได้':'Roll lại cả STAT lẫn giá trị (+1~{a}) — có thể ra y như cũ',
  'สุ่มใหม่ทั้ง STAT และค่า (+1~{a})':'Roll lại cả STAT lẫn giá trị (+1~{a})',
  '🎲 สุ่มเลย':'🎲 Roll luôn!',
  // ── 🎯 เลือกสเตตัสสกิน ──
  '🎯 เลือก STAT':'🎯 Chọn STAT', '🎯 เลือก STAT {a}P':'🎯 Chọn STAT {a}P',
  '🎯 เลือก STAT — {a}':'🎯 Chọn STAT — {a}',
  'ได้ +{a} เต็มเพดาน · ราคา {b} P':'Nhận +{a} kịch trần · giá {b} P',
  '🎯 เลือก STAT เอง ได้ +{a} เต็มเพดาน · เลือกใหม่ได้ {b}P/ครั้ง':'🎯 Tự chọn STAT nhận +{a} kịch trần · chọn lại {b}P/lần',
  'แตะ STAT เพื่อยืนยันซื้อ':'Chạm STAT để xác nhận mua',
  '🎲 รีโรลสกินแล้ว':'🎲 Đã roll lại skin', '🎲 รีโรลสกินฮีโร่แล้ว':'🎲 Đã roll lại skin Hero', '🎲 รีโรลสัตว์เลี้ยงแล้ว':'🎲 Đã roll lại đồng hành',
  'รีโรลไม่สำเร็จ':'Roll lại thất bại',
  '❌ รีโรลไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Roll lại thất bại (không kết nối được server)',
  '❌ รีโรลสกินฮีโร่ไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Roll lại skin Hero thất bại (không kết nối được server)',
  '❌ รีโรลสัตว์เลี้ยงไม่สำเร็จ (เชื่อมต่อ server ไม่ได้)':'❌ Roll lại đồng hành thất bại (không kết nối được server)',
  '🎨 เปลี่ยนสกินไททันแล้ว':'🎨 Đã đổi skin Titan', '🤖 กลับเป็น Bob ไททันคู่ใจ':'🤖 Trở lại Bob, Titan thân thiết',
  '🗡️ เปลี่ยนสกินฮีโร่แล้ว':'🗡️ Đã đổi skin Hero', '🧑 กลับเป็นนักรบฝึกหัด':'🧑 Trở lại Chiến binh tập sự',
  '🐾 เปลี่ยนสัตว์เลี้ยงแล้ว':'🐾 Đã đổi đồng hành', '🐕 กลับเป็นส้มจี๊ด คู่หูคนแรก':'🐕 Trở lại Somjeed, bạn đồng hành đầu tiên',
  'เปลี่ยนสกินไม่สำเร็จ':'Đổi skin thất bại', 'เปลี่ยนสัตว์เลี้ยงไม่สำเร็จ':'Đổi đồng hành thất bại',
  // ── คู่มือ Premium (PREMIUM_HELP) ──
  'แต้ม P (P Point)':'Điểm P (P Point)',
  'สกุลเงิน Premium — ได้จากการเติมเงินเท่านั้น\nดูยอด P Point คงเหลือได้ด้านบนของหน้า Premium Shop':'Tiền tệ Premium — chỉ có được từ việc nạp\nXem số dư P Point ở đầu trang Premium Shop',
  'วิธีซื้อ Premium Item':'Cách mua Premium Item',
  'เลือก Item ที่ต้องการ → กดซื้อ → ยืนยัน\nระบบจะหักแต้ม P และเปิดใช้งานทันที':'Chọn item mong muốn → bấm mua → xác nhận\nHệ thống trừ điểm P và kích hoạt ngay',
  'ระยะเวลา 10 วัน':'Thời hạn 10 ngày',
  'แต่ละ Item มีอายุการใช้งาน 10 วันนับจากวันที่ซื้อ\nหน้าจอแสดงวัน/เวลาหมดอายุและเวลาที่เหลืออย่างละเอียด':'Mỗi item có hạn dùng 10 ngày kể từ ngày mua\nMàn hình hiển thị chi tiết ngày/giờ hết hạn và thời gian còn lại',
  'ซื้อต่อ = ต่ออายุอัตโนมัติ':'Mua tiếp = tự động gia hạn',
  'ถ้ายังมีเวลาเหลืออยู่ การซื้อซ้ำจะบวก 10 วันต่อจากวันเดิม\nสะสมได้ไม่จำกัด ยิ่งซื้อไว ยิ่งได้นาน':'Nếu còn thời gian, mua lại sẽ cộng thêm 10 ngày\nCộng dồn không giới hạn — mua càng sớm, dùng càng lâu',
  'รับ EXP เพิ่ม 35% ทุกครั้งที่กำจัดมอนสเตอร์\nแสดงใน Log แยกบรรทัด: 🅿️ EXP+N':'Nhận thêm 35% EXP mỗi lần hạ quái\nHiển thị trong Log ở dòng riêng: 🅿️ EXP+N',
  'รับ Gold เพิ่ม 35% ทุกครั้งที่กำจัดมอนสเตอร์\nแสดงใน Log แยกบรรทัด: 🅿️ G+N':'Nhận thêm 35% Gold mỗi lần hạ quái\nHiển thị trong Log ở dòng riêng: 🅿️ G+N',
  'ทุกคิลล์สุ่มได้แร่ 1-3 ชิ้น (ไม้/หิน/เหล็ก/ทองแดง/พืช) · ชนิดเดียวต่อคิลล์\nปลดเหมือง #4 ที่ยานบิน (ผลิตเฉพาะช่วง Premium · หมดอายุ = พัก เก็บเลเวลไว้)\nแสดงใน Log: 🅿️ ⛏️ ได้ 🪨หิน +2':'Mỗi kill nhận ngẫu nhiên 1-3 quặng (gỗ/đá/sắt/đồng/cây) · một loại mỗi kill\nMở Mỏ #4 trên phi thuyền (chỉ sản xuất khi Premium còn hạn · hết hạn = nghỉ, giữ cấp)\nHiển thị trong Log: 🅿️ ⛏️ nhận 🪨đá +2',
  // ── ตลาด (renderMarket/_mkt*) ──
  '🔍 ค้นหา...':'🔍 Tìm kiếm...', '🏷️ + วางขาย':'🏷️ + Rao bán', '🛒 ซื้อ':'🛒 Mua', '📦 ของฉัน':'📦 Của tôi', '🧾 ประวัติ':'🧾 Lịch sử',
  'ทั้งหมด':'Tất cả', '🗃️ ของวิเศษ':'🗃️ Đồ sưu tầm', '🔧 โมดูล':'🔧 Module', '🎁 กล่อง/ไข่':'🎁 Hộp/Trứng',
  'ทรัพยากร':'Tài nguyên', '💎 เพชร':'💎 Kim cương', '🔫 กระสุน':'🔫 Đạn',
  '🗃️ ของวิเศษ ชิ้นส่วนไททัน':'🗃️ Linh kiện Titan', '🗃️ ของวิเศษ ชิ้นส่วนอาวุธ':'🗃️ Linh kiện vũ khí',
  '🗃️ ของวิเศษ ชิ้นส่วนยานบิน':'🗃️ Linh kiện phi thuyền', '🗃️ ของวิเศษ ชิ้นส่วนสเตตัส':'🗃️ Linh kiện chỉ số',
  '🎴 การ์ดมอน':'🎴 Thẻ quái',
  '🔪 โมดูลมีดสั้น':'🔪 Module dao găm', '🗡️ โมดูลมีดยาว':'🗡️ Module dao dài', '🗡️ โมดูลดาบ':'🗡️ Module kiếm',
  '🪓 โมดูลขวาน':'🪓 Module rìu', '🔋 โมดูลไททัน':'🔋 Module Titan', '🦾 โมดูลธนูไททัน (ARM)':'🦾 Module cung Titan (ARM)',
  '⚡ โมดูล Premium Titan Beam':'⚡ Module Premium Titan Beam', '🛡️ โมดูลเกราะ':'🛡️ Module giáp',
  '🛸 โมดูลยานบิน':'🛸 Module phi thuyền', '🗼 โมดูลป้อม':'🗼 Module pháo tháp', '🥚 ไข่สัตว์เลี้ยง':'🥚 Trứng thú cưng',
  'โมดูลดาบ':'Module kiếm',
  'ระดับโมดูล':'Bậc Module', 'ความหายาก':'Độ hiếm',
  'ขาว':'Trắng', 'เขียว':'Xanh lá', 'ฟ้า':'Xanh dương', 'ม่วง':'Tím', 'ทอง':'Vàng', 'แดง':'Đỏ',
  '🏷️ วางขาย — เลือกของ':'🏷️ Rao bán — chọn đồ', '🏷️ วางขาย — ตั้งราคา':'🏷️ Rao bán — đặt giá',
  'ยังไม่มีของในหมวดนี้':'Chưa có đồ trong mục này', 'ลองเลือกหมวดอื่น หรือออกไปเก็บของเพิ่ม':'Thử mục khác hoặc đi kiếm thêm đồ nhé',
  'จำนวน':'Số lượng', 'ราคา/ชิ้น':'Giá/món', '💡 ราคาตลาดตอนนี้: เริ่ม {a}G':'💡 Giá chợ hiện tại: từ {a}G',
  'รับสุทธิ (หัก fee 5%): ':'Thực nhận (trừ phí 5%): ',
  'สินค้าจะหมดอายุใน 24 ชม. — กด "ยกเลิก" ในแท็บของฉันเพื่อรับของคืน':'Hàng hết hạn sau 24 giờ — bấm "Hủy" trong tab Của tôi để nhận lại đồ',
  '🏷️ วางขายเลย':'🏷️ Rao bán luôn!',
  '{a} ประกาศ':'{a} tin rao', 'เริ่ม {a}G':'từ {a}G', '{a} ชิ้น':'{a} món', 'ไม่พบสินค้า':'Không tìm thấy hàng',
  '‹ กลับ':'‹ Quay lại', 'สินค้า':'Hàng hóa', 'ไม่มีประกาศขายแล้ว':'Không còn tin rao nào', '/ชิ้น':'/món', 'ซื้อ':'Mua',
  'หายาก+':'Hiếm+', 'มีตีบวก':'Đã cường hóa', 'ไม่มีประกาศในหมวดนี้':'Không có tin rao trong mục này',
  'กล่องการ์ด Lv.{a}-{b}':'Hộp thẻ Lv.{a}-{b}', 'กล่องโมดูล{a}':'Hộp Module: {a}',
  'สุ่มการ์ดมอน Lv.{a}-{b} · ⭐MVP 1%':'Thẻ quái ngẫu nhiên Lv.{a}-{b} · ⭐MVP 1%',
  'สุ่มโมดูล rarity {a} ({b} รู) ทุกอาวุธ':'Module ngẫu nhiên độ hiếm {a} ({b} ô khảm), mọi vũ khí',
  'มี ×{a} ใบ':'Có ×{a}', 'มี ×{a} ฟอง':'Có ×{a}',
  'ฟักเป็นสัตว์เลี้ยง':'Ấp thành thú cưng',
  '⚠️ คลังโมดูลเต็ม (30) — ทำลาย/ติดตั้งก่อนซื้อ':'⚠️ Kho Module đầy (30) — phá hủy/lắp bớt trước khi mua',
  '🔧 โมดูลรายชิ้น — จะเข้าคลังโมดูลของคุณ':'🔧 Module lẻ — sẽ vào kho Module của bạn',
  '💎 เพชร — จะเพิ่มเข้าคลังของคุณ':'💎 Kim cương — cộng vào kho của bạn', '📦 ทรัพยากร — จะเพิ่มเข้าคลังของคุณ':'📦 Tài nguyên — cộng vào kho của bạn',
  '✨ ของชิ้นนี้คุณยังไม่มี — ซื้อแล้วจะได้เป็นของใหม่!':'✨ Món này bạn chưa có — mua là đồ mới toanh!',
  '📦 คุณมีของชิ้นนี้อยู่แล้ว — จะเพิ่มจำนวน':'📦 Bạn đã có món này — số lượng sẽ tăng thêm',
  'ยืนยันการซื้อ':'Xác nhận mua', 'ขายโดย {a}':'Bán bởi {a}', 'ราคา':'Giá', '{a} G / ชิ้น':'{a} G / món',
  'ทองที่มี':'Gold đang có', 'รวม':'Tổng', 'คงเหลือหลังซื้อ':'Còn lại sau khi mua', 'ทองไม่พอ':'Không đủ Gold', '🛒 ซื้อเลย':'🛒 Mua luôn',
  'ซื้อสำเร็จ!':'Mua thành công!', '{a} จาก {b}':'{a} từ {b}', 'เข้ากระเป๋าแล้ว':'Đã vào túi', 'ซื้อต่อ':'Mua tiếp',
  'ไม่มีสินค้าที่วางขายอยู่':'Không có hàng đang rao', 'เหลือ {a} ชม.':'Còn {a} giờ',
  'วางขายสำเร็จ':'Rao bán thành công', 'ไม่สามารถซื้อได้: ':'Không thể mua: ',
  'ยกเลิกรายการนี้?':'Hủy tin rao này?', 'ไม่สามารถยกเลิกได้':'Không thể hủy',
  'ขายได้':'Đã bán', 'ซื้อมา':'Đã mua', 'หมดอายุ':'Hết hạn', 'ลงขาย':'Đã rao',
  '7 วันที่ผ่านมา · ขาย {a} รายการ · ซื้อ {b} รายการ':'7 ngày qua · bán {a} · mua {b}',
  // ── PVP/แผนที่/อื่นๆ ──
  'PVP — ดวลผู้เล่น':'PVP — đấu tay đôi',
  'DMG ÷30 · แพ้กลับกลางแมพ · ไม่เสียของ':'DMG ÷30 · thua về giữa bản đồ · không mất gì',
  'ท้าดวล':'Khiêu chiến', 'ประวัติ':'Lịch sử',
  'ยังไม่มีผู้เล่นอื่นในระบบ':'Chưa có người chơi khác',
  '🏳️ ยอมแพ้/ออกจากดวลปัจจุบัน':'🏳️ Đầu hàng / rời trận đấu hiện tại',
  '⚔️ ดวล':'⚔️ Đấu',
  'ท้าดวล {a}?\n\n⚔️ DMG ÷30 · สู้จน HP หมด\n💀 ผู้แพ้กลับกลางแมพ (ไม่เสียของ)':'Khiêu chiến {a}?\n\n⚔️ DMG ÷30 · đấu đến cạn HP\n💀 Người thua về giữa bản đồ (không mất gì)',
  'เมื่อครู่':'vừa xong', '{a} นาทีก่อน':'{a} phút trước', '{a} ชม.ก่อน':'{a} giờ trước', '{a} วันก่อน':'{a} ngày trước',
  'ชนะ':'thắng', '⏱️ {a} วิ':'⏱️ {a}s', '{a} ชนะ':'{a} trận thắng', 'คุณ':'Bạn',
  'ยังไม่มีการดวล — เป็นคนแรกสิ!':'Chưa có trận đấu nào — làm người đầu tiên đi!',
  'ยังไม่มีแชมป์ — ตารางว่างรอคุณอยู่':'Chưa có nhà vô địch — bảng xếp hạng đang chờ bạn',
  'ยอมแพ้ดวลนี้? (นับเป็นแพ้ถ้าสู้เริ่มแล้ว)':'Đầu hàng trận này? (tính là thua nếu đã bắt đầu đánh)',
  'ท้าดวลคุณ!':'khiêu chiến bạn!',
  'Lv.{a} · DMG ÷30 · แพ้กลับกลางแมพ (ไม่เสียของ)':'Lv.{a} · DMG ÷30 · thua về giữa bản đồ (không mất gì)',
  '⚔️ รับคำท้า':'⚔️ Nhận lời', '🏃 ปฏิเสธ':'🏃 Từ chối',
  '⚔️ มีคำท้า!':'⚔️ Có lời khiêu chiến!', '⚔️ กำลังดวล':'⚔️ Đang đấu',
  '🏃 วิ่งเข้าหา {a} — อีก {b}m':'🏃 Chạy đến chỗ {a} — còn {b}m',
  '⏱️ เหลือ {a}s (หมดเวลา = เสมอ)':'⏱️ Còn {a}s (hết giờ = hòa)',
  // ── แผนที่ (openMapSelect/warpToMap) ──
  '🗺️ เปลี่ยนแผนที่':'🗺️ Đổi bản đồ',
  'ทุ่งกลาง':'Cánh đồng trung tâm', 'ทะเลทรายนิรันดร์':'Sa mạc vĩnh hằng', 'ดินแดนเยือกแข็ง':'Vùng đất băng giá',
  // ── 🏛️ สนามประลอง (Colosseum · map 4) ──
  'สนามประลอง':'Đấu trường',
  '🔄 แลก ⭐MVP':'🔄 Đổi ⭐MVP',
  '🔄 แลก':'🔄 Đổi',
  'ไข่ปกติ':'Trứng thường',
  'ใช้ไข่ปกติ {a} ฟอง → เหลือ {b} ฟอง':'Dùng {a} trứng thường → còn {b}',
  'ยังแลกไม่ได้ — ต้องสะสมให้ครบ {a} ฟองก่อน':'Chưa đổi được — gom đủ {a} trước',
  'มี {a} ฟอง · ขาดอีก {b} ฟอง':'Có {a} · thiếu {b}',
  'แลกไข่ ⭐MVP':'Đổi thành trứng ⭐MVP',
  'แลกไข่ไม่สำเร็จ':'Đổi thất bại',
  '🔄 ไข่ปกติ {a} ฟอง = ไข่ ⭐MVP 1 ฟอง':'🔄 {a} trứng thường = 1 trứng ⭐MVP',
  'กดปุ่มแลกที่ไข่ MVP':'Nhấn Đổi ở trứng MVP',
  'พลังแรงกว่า ×2':'Mạnh gấp 2',
  '🔄 การ์ดปกติ {a} ใบ = การ์ด ⭐MVP 1 ใบ':'🔄 {a} thẻ thường = 1 thẻ ⭐MVP',
  'กดปุ่มแลกที่การ์ด MVP':'Nhấn Đổi ở thẻ MVP',
  'ยังแลกไม่ได้ — ต้องสะสมให้ครบ {a} ใบก่อน':'Chưa đổi được — gom đủ {a} trước',
  'มี {a} ใบ · ขาดอีก {b} ใบ':'Có {a} · thiếu {b}',
  'เข้าใจแล้ว':'Đã hiểu',
  'ต้องครบ {a}':'Cần {a}',
  'การ์ดปกติไม่พอ (ต้องมี {a} ใบ)':'Không đủ thẻ thường (cần {a})',
  'แลกการ์ด ⭐MVP':'Đổi thành thẻ ⭐MVP',
  'ใช้การ์ดปกติ {a} ใบ → เหลือ {b} ใบ':'Dùng {a} thẻ thường → còn {b}',
  '✅ แลกเลย':'✅ Đổi ngay',
  'แลกการ์ดไม่สำเร็จ':'Đổi thất bại',
  'การ์ดปกติ':'Thẻ thường',
  '⚔️ PVP อิสระ · {a} คนในสนาม':'⚔️ PVP tự do · {a} người trong sân',
  '🏛️ {a} คน':'🏛️ {a} người',
  '🏛️ อันดับสังหารวันนี้ — รีเซ็ตเที่ยงคืน':'🏛️ BXH hạ gục hôm nay — reset lúc nửa đêm',
  'วันนี้ยังไม่มีการต่อสู้ในสนาม':'Hôm nay chưa có trận đấu nào trong sân',
  'ประลอง(แท็บ)':'Đấu trường',
  // ── ชื่อแผนที่/โซน (XHRPG_SPOTS ทั้ง 3 แมพ) ──
  'ป่าสนตะวันออก':'Rừng thông phía đông', 'หุบเขาลึกลับ':'Thung lũng huyền bí', 'รังสไลม์เหนือ':'Ổ Slime phía bắc',
  'ทุ่งสไลม์ตะวันตก':'Đồng Slime phía tây', 'ป่ามืดมน':'Rừng u tối',
  'โอเอซิส':'Ốc đảo', 'ป่าเห็ดตะวันออก':'Rừng nấm phía đông', 'รังหนูตะวันตก':'Ổ chuột phía tây',
  'ถ้ำกิ้งก่าใต้':'Hang thằn lằn phía nam', 'ค่ายหมาป่าเหนือ':'Trại sói phía bắc', 'แอ่งสไลม์อสูร':'Lòng chảo Slime quỷ',
  'ต้นไม้น้ำแข็ง':'Cây băng giá', 'สุสานโบราณ':'Nghĩa địa cổ', 'พื้นที่รกร้าง':'Vùng đất hoang tàn',
  '📍 อยู่ที่นี่':'📍 Bạn đang ở đây', '🔒 ต้องถึง Lv.{a}':'🔒 Cần đạt Lv.{a}', 'พร้อมวาร์ป · Lv.{a}+':'Sẵn sàng dịch chuyển · Lv.{a}+',
  'แผนที่ {a}':'Bản đồ {a}', '🗺️ วาร์ปไป {a}!':'🗺️ Đã dịch chuyển đến {a}!',
  'วาร์ปไม่สำเร็จ: ตอบกลับผิดรูปแบบ':'Dịch chuyển thất bại: phản hồi sai định dạng',
  'ต้องถึง Lv.{a} ก่อนวาร์ป':'Cần đạt Lv.{a} mới dịch chuyển được', 'ต้องถึง Lv.{a}':'Cần đạt Lv.{a}',
  'วาร์ปไม่สำเร็จ: ':'Dịch chuyển thất bại: ',
  '❌ วาร์ปไม่สำเร็จ (เชื่อมต่อไม่ได้ HTTP {a})':'❌ Dịch chuyển thất bại (mất kết nối, HTTP {a})',
  // ── เดินทาง/บอส/อื่นๆ ──
  'บอสตัวนี้หายไปแล้ว':'Boss này biến mất rồi',
  '{a} กำลังไปล่าบอส {b} (Lv.{c})!':'{a} Đang đi săn Boss {b} (Lv.{c})!',
  '{a} กำลังเดินไป {b} (Lv.{c}-{d})...':'{a} Đang đi đến {b} (Lv.{c}-{d})...',
  '✅ ถึงโซนแล้ว! เริ่มโจมตี (หยุดรอบนอก ~80m)':'✅ Đã đến khu! Bắt đầu tấn công (dừng vòng ngoài ~80m)',
  'ยังไม่มียานบิน':'Bạn chưa có phi thuyền',
  '🛸 กำลังเดินทางไปยานบิน...':'🛸 Đang đi về phi thuyền...',
  '🛸 Warp กลางแผนที่!':'🛸 Dịch chuyển về giữa bản đồ!',
  'ชื่อต้องมี 2–16 ตัวอักษร':'Tên phải dài 2–16 ký tự',
  'ถูก Kick ออกจากระบบ':'Bị kick khỏi hệ thống',
  'มีการเข้าสู่ระบบจากอุปกรณ์อื่น<br>กรุณา Login ใหม่':'Có đăng nhập từ thiết bị khác<br>Vui lòng đăng nhập lại',
  '🔄 Login ใหม่':'🔄 Đăng nhập lại',
  // ── เดโม log (startDemo) ──
  '✨ ได้รับ 🔧 สายธนูอัพเกรด (ซ้ำ x2)':'✨ Nhận 🔧 Dây cung nâng cấp (trùng x2)',
  '✨ ได้รับ 🌿 ท่อนไม้มหัศจรรย์':'✨ Nhận 🌿 Khúc gỗ kỳ diệu',
  '✨ ได้รับ ⚙️ ชิ้นส่วนไททัน III':'✨ Nhận ⚙️ Linh kiện Titan III',
  '✨ ได้รับ 💊 สารสกัดพิเศษ (ซ้ำ x3)':'✨ Nhận 💊 Tinh chất đặc biệt (trùng x3)',
  '💊 ดื่มยา HP +80 (80/100)':'💊 Uống thuốc HP +80 (80/100)',
  '🎉 LEVEL UP! Lv.2 → Lv.3 รับ Stat Point +1':'🎉 LEVEL UP! Lv.2 → Lv.3 — Stat Point +1',
  '✨ ได้รับ 🛸 โครงยานบินเสริม':'✨ Nhận 🛸 Khung phi thuyền phụ',
  '🛸 ยานบินผลิต มีดสั้น +12':'🛸 Phi thuyền sản xuất dao găm +12',
  '✨ ได้รับ 💍 แหวนนักรบ Tier 2':'✨ Nhận 💍 Nhẫn chiến binh Tier 2',
  // ── คู่มือ (renderGuide) ──
  'เรื่องราวของ Ragnalok':'Câu chuyện Ragnalok', 'เริ่มการผจญภัย ⚔️':'Bắt đầu cuộc phiêu lưu ⚔️',
  'เรื่องราว':'Cốt truyện',
  'บทที่ 0 : จุดกำเนิดแห่งความหวัง':'Chương 0 : Khởi nguồn hy vọng',
  'ภาพรวมหน้าจอ':'Tổng quan màn hình',
  'แผนที่ (Canvas)':'Bản đồ (Canvas)',
  'พื้นที่หลักที่ตัวละครเดินและต่อสู้ มุมซ้ายบนแสดง Minimap รวมตำแหน่งผู้เล่นคนอื่น ยานบิน และมอนสเตอร์ที่อยู่ใกล้เคียง':'Khu vực chính nơi nhân vật di chuyển và chiến đấu. Góc trên trái hiển thị minimap với người chơi khác, phi thuyền và quái gần đó.',
  'แถบ HP / EXP':'Thanh HP / EXP',
  'HP (แดง) แสดงเลือดปัจจุบัน ถ้าถึง 0 ตาย Respawn อัตโนมัติ EXP (น้ำเงิน) เมื่อเต็ม Level Up รับ Stat Point 1 แต้ม':'HP (đỏ) là máu hiện tại — về 0 sẽ chết và tự hồi sinh. EXP (xanh dương) — đầy thanh là lên cấp, nhận 1 Stat Point.',
  'ทองและ P-Points':'Gold & P-Points',
  'Gold (G) ใช้ซื้อของในตลาดและอัปเกรด อยู่มุมขวาบนแผนที่ P-Points ใช้เปิดสิทธิ์ Premium':'Gold (G) dùng mua đồ ở chợ và nâng cấp; nằm góc trên phải bản đồ. P-Points mở các đặc quyền Premium.',
  'ปุ่มเมนูด้านล่าง':'Nút menu bên dưới',
  'แถว 1: อาวุธ / ไอเทม / STAT / ไททัน / ยานบิน  แถว 2: การ์ด / ตลาด / สัตว์เลี้ยง / อันดับ / Premium · 📖 คู่มือย้ายไปปุ่มกลมมุมซ้ายบนของแผนที่ (ใต้ไอคอน FB)':'Hàng 1: Vũ khí / Vật phẩm / STAT / Titan / Phi thuyền  Hàng 2: Thẻ bài / Chợ / Thú cưng / Xếp hạng / Premium · 📖 Cẩm nang chuyển sang nút tròn góc trên trái bản đồ (dưới icon FB)',
  'ระบบ Auto และการเดิน':'Auto & di chuyển',
  'เปิด/ปิด Auto':'Bật/tắt Auto',
  'กดปุ่ม AUTO บนหน้าจอ เมื่อเปิด ตัวละครจะเดินหาศัตรูและโจมตีอัตโนมัติตลอดเวลา แม้ปิดหน้าจอ':'Bấm nút AUTO trên màn hình. Khi bật, nhân vật tự tìm địch và tấn công liên tục, kể cả khi tắt màn hình.',
  'LOCK ATK (ยืนตีกับที่)':'LOCK ATK (đứng đánh tại chỗ)',
  'กดปุ่ม 🔒 LOCK ATK ใต้ปุ่ม AUTO ตัวละครจะหยุดเดิน ยืนนิ่งอยู่กับที่ แล้วขว้างใส่มอนที่เข้ามาในระยะ เหมาะเวลาอยากคุมจุดหรือฟาร์มจุดเดียว · กดอีกครั้งเพื่อปลดล็อค':'Bấm nút 🔒 LOCK ATK dưới nút AUTO. Nhân vật ngừng đi, đứng yên tại chỗ và ném vào quái lọt tầm — hợp khi muốn giữ điểm hoặc farm một chỗ · bấm lần nữa để mở khóa.',
  'ปรับช่วงที่ตัวละครเดินออกจากจุดศูนย์กลาง (ยานบิน หรือจุด Spawn) ค่ายิ่งสูงยิ่งเจอมอนหลากหลายและ Level สูงขึ้น':'Chỉnh phạm vi nhân vật đi xa khỏi điểm trung tâm (phi thuyền hoặc điểm spawn). Giá trị càng cao gặp quái càng đa dạng và cấp cao hơn.',
  'ทิศทางเดิน':'Đi thủ công',
  'กดลูกศร ↑↓←→ ควบคุมเดินด้วยตนเอง หรือกด Warp Home เพื่อกลับหน้ายานบินทันที':'Bấm mũi tên ↑↓←→ để tự điều khiển, hoặc bấm Warp Home để về ngay phi thuyền.',
  'การสำรวจแบบสุ่ม':'Khám phá ngẫu nhiên',
  'แต่ละผู้เล่นมีมุมสุ่มเฉพาะตัว ทำให้เส้นทางเดินไม่ซ้ำกัน ลดการกระจุกตัว':'Mỗi người chơi có góc ngẫu nhiên riêng, nên lộ trình không trùng nhau, giảm dồn cục.',
  'อาวุธและการต่อสู้':'Vũ khí & chiến đấu',
  'ขว้างเร็ว แม่นยำ กระสุนเยอะ เหมาะทำ DPS ต่อเนื่อง อัปเกรด Level เพิ่ม ATK และความจุสูงสุด':'Ném nhanh, chuẩn xác, nhiều đạn — hợp đánh DPS liên tục. Nâng cấp để tăng ATK và sức chứa tối đa.',
  'ดาเมจสูงต่อนัด ระยะไกล แต่กระสุนน้อยกว่า เหมาะฆ่า MVP ที่ HP สูง':'Sát thương cao mỗi phát, tầm xa nhưng ít đạn hơn — lý tưởng để hạ MVP máu trâu.',
  'มีด (Knife)':'Dao (cận chiến)',
  'โจมตีอัตโนมัติระยะประชิด 5m เมื่อศัตรูเข้ามาใกล้ ไม่ใช้มีดสั้น':'Tự đánh cận chiến 5m khi địch áp sát. Không tốn dao găm.',
  'ไททัน Robot':'Robot Titan',
  'มี 3 โหมด: Axe (ระยะใกล้), ธนูไททัน ARM (ยิง), Premium Titan Beam (ชาร์จแล้วระเบิด) ต้องการพลังงาน Robot Energy':'Có 3 chế độ: Rìu (tầm gần), cung Titan ARM (bắn), Premium Titan Beam (sạc rồi nổ). Cần Robot Energy.',
  'กระสุน T1-T6':'Đạn T1-T6',
  'กระสุนแต่ละชนิดมี 6 ระดับ ⚪T1→🔴T6 ยิ่ง T สูง DMG คูณมากขึ้น (×1.0→×2.0)\nเปิด/ปิดแต่ละ T ได้ ระบบเลือกใช้ T สูงสุดที่เปิดและมีกระสุนก่อน\nปลดล็อค T สูงตามเลเวลยานบิน\nความจุพก: T1 = 50 +5/เลเวลผู้เล่น · T สูงถือน้อยลง (ไม่ขึ้นกับ STR แล้ว)':'Mỗi loại đạn có 6 tier ⚪T1→🔴T6 — T càng cao hệ số DMG càng lớn (×1.0→×2.0)\nBật/tắt từng T; hệ thống ưu tiên T cao nhất đang bật và còn đạn\nT cao mở khóa theo cấp phi thuyền\nSức chứa mang theo: T1 = 50 +5/cấp người chơi · T cao mang ít hơn (không còn theo STR)',
  'กดปุ่มสลับในเมนูอาวุธ ระหว่าง มีดสั้น / มีดยาว อาวุธที่ไม่ใช้งานจะหยุดขว้าง':'Bấm nút đổi trong menu vũ khí giữa Dao găm / Dao dài. Vũ khí không dùng sẽ ngừng ném.',
  'กระสุน (Ammo)':'Đạn (Ammo)',
  'กระสุนหมดตัวละครหยุดขว้าง กด Auto Refill ให้เติมกระสุนจากกระเป๋าอัตโนมัติ หรือเติมเองในเมนูอาวุธ':'Hết đạn nhân vật ngừng ném. Bật Auto Refill để tự nạp từ túi, hoặc nạp tay trong menu vũ khí.',
  'สถานะ (STAT) และ Skill':'Chỉ số (STAT) & Skill',
  'ATK ดาบ (melee) +3/แต้ม · 🛡️ เกราะสูงสุด +1 ทุก 2 STR (แบบ VIT) · 💥 คริ +1% ทุก 10 STR (รวมกับ LUK)':'ATK kiếm (cận chiến) +3/điểm · 🛡️ Giáp tối đa +1 mỗi 2 STR (kiểu VIT) · 💥 Crit +1% mỗi 10 STR (cộng với LUK)',
  'เพิ่มความเร็วเดิน · โอกาสหลบมอน = floor(AGI/2) − (เลเวลมอน−1) % (เพดาน 75% · MVP ครึ่ง)':'Tăng tốc độ đi · tỷ lệ né quái = floor(AGI/2) − (cấp quái−1) % (tối đa 75% · MVP giảm nửa)',
  'ATK ขว้างมีดสั้น +2.0/แต้ม · มีดยาว +2.5/แต้ม · ระยะขว้าง +1m ทุก 24 DEX':'ATK ném dao găm +2.0/điểm · dao dài +2.5/điểm · tầm ném +1m mỗi 24 DEX',
  'MP สูงสุด +5/แต้ม · MP ฟื้น +1 ทุก 5 · ฟื้นพลังงานไททัน +1 ทุก 10 · ATK ป้อม +3/แต้ม':'MP tối đa +5/điểm · hồi MP +1 mỗi 5 · hồi năng lượng Titan +1 mỗi 10 · ATK pháo tháp +3/điểm',
  'HP สูงสุด +1/แต้ม · เกราะสูงสุด/ฟื้นเกราะ · HP ฟื้น +1 ทุก 5 · ความจุยา +2/แต้ม (ต่อระดับยา)':'HP tối đa +1/điểm · giáp tối đa/hồi giáp · hồi HP +1 mỗi 5 · sức chứa thuốc +2/điểm (mỗi bậc thuốc)',
  'โอกาสคริ ×2 = floor((LUK+STR)/10)% สูงสุด 50% (LUK+STR รวมกัน) · โอกาสดรอปทรัพยากร/สมุนไพร +0.75% ทุก 5 LUK (LUK5 = 25% · เพดาน 48%) · โบนัสจำนวน: 30% ลุ้นได้เพิ่มสุ่ม 1..floor(LUK/15) เริ่มมีผลที่ LUK 15':'Tỷ lệ Crit ×2 = floor((LUK+STR)/10)%, tối đa 50% (cộng LUK+STR) · tỷ lệ rơi tài nguyên/thảo dược +0.75% mỗi 5 LUK (LUK5 = 25% · trần 48%) · thưởng số lượng: 30% cơ hội thêm ngẫu nhiên 1..floor(LUK/15), có hiệu lực từ LUK 15',
  'ได้รับ 1 แต้มต่อ Level Up กด STAT เพื่อแจกแต้ม ดู badge สีแดงที่ปุ่มเมื่อมีแต้มค้างอยู่':'Nhận 1 điểm mỗi lần lên cấp. Bấm STAT để cộng điểm — badge đỏ trên nút nghĩa là còn điểm chưa dùng.',
  'เปิดเมนูทักษะ เพื่อ unlock และ auto-use Skill ใช้ MP เมื่อสู้':'Mở menu kỹ năng để mở khóa và tự dùng Skill. Skill tốn MP khi chiến đấu.',
  'ของสะสมและ Equipment':'Đồ sưu tầm & Equipment',
  'ของวิเศษ':'Bảo vật',
  'ประเทศ':'Quốc gia',
  'พลังรบรวม':'Tổng sức mạnh',
  'นับจาก Top {a} · ผู้เล่น {b} คน':'từ Top {a} · {b} người chơi',
  '♻️ ทำลายแล้ว <b>🎴 การ์ดที่เสียบคืนเข้าคลัง</b> · ค่าตีบวก (เพชร+ทอง) ไม่คืน':'♻️ Phân hủy trả lại <b>🎴 thẻ đã khảm</b> · phí cường hóa (đá quý+vàng) KHÔNG hoàn',
  'ทำลายแล้วกู้คืนไม่ได้ · การ์ดที่เสียบคืนเข้าคลัง · ค่าตีบวกไม่คืน':'Không thể hoàn tác · thẻ đã khảm được trả lại · phí cường hóa KHÔNG hoàn',
  'ใบ':'thẻ',
  '/ใบ':'/thẻ',
  'ทุกประเทศ':'Tất cả quốc gia',
  'กรองประเทศ':'Lọc quốc gia',
  'เลือกประเทศ':'Chọn quốc gia',
  'ยังไม่มีข้อมูลประเทศ':'Chưa có dữ liệu quốc gia',
  'พักหน้าจอ — เข้าโหมดออฟไลน์':'Màn hình tạm dừng — chế độ offline',
  'ไม่มีการใช้งานเกิน 10 นาที · ฟาร์มออฟไลน์เดินต่อให้อยู่':'Không hoạt động hơn 10 phút · farm offline vẫn tiếp tục',
  'แตะเพื่อเล่นต่อ':'Chạm để chơi tiếp',
  'นักบวช':'Tu sĩ',
  'พลังงานหุ่น':'Năng lượng Titan',
  'เช่าที่ร้าน PREMIUM':'Thuê tại cửa hàng PREMIUM',
  'นักธนู':'Cung thủ',
  'ยิงมอน':'Bắn quái',
  'ธนูระเบิดทุก 3 นัด':'Mũi tên nổ mỗi 3 phát',
  'ยิงมอนทุกวินาที · ระเบิดทุก 3 นัด':'Bắn mỗi giây · nổ mỗi 3 phát',
  'ระเบิด':'Nổ',
  'ระยะ':'Tầm',
  'นักธนูเดินตาม — ยิงธนูใส่มอนทุกวินาที · DMG = Premium Titan Beam · 💥 ธนูระเบิดทุก 3 นัด DMG×3 AOE | ระยะ 150m +0.25m/Lv | อัพเกรดได้ Lv.1-100':'Cung thủ đi theo — bắn tên vào quái mỗi giây · DMG = Premium Titan Beam · 💥 mũi tên nổ mỗi 3 phát DMG×3 AOE | tầm 150m +0.25m/Lv | nâng cấp Lv.1-100',
  'ทุกวินาที เลือกสกิลตามที่พร่อง (Heal ก่อน)':'Mỗi giây chọn kỹ năng theo thứ đang thiếu (Hồi máu trước)',
  'วัน':'ngày',
  'นักบวชเดินตาม — ทุกวินาที เลือกสกิลตามที่พร่อง (Heal ก่อน): 💚Heal HP / 💧Heal MP / 🛡️บัฟ DEF 30s (เรา+หุ่น+สัตว์เลี้ยง) / 🔰ฟื้นเกราะ / ⚡เติมพลังหุ่น / 🧱บัฟ MAX เกราะ | อัพเกรดได้ Lv.1-100':'Tu sĩ đi theo bạn — mỗi giây chọn kỹ năng theo thứ đang thiếu (Hồi máu trước): 💚Hồi HP / 💧Hồi MP / 🛡️buff DEF 30s (bạn+Titan+thú cưng) / 🔰hồi giáp / ⚡nạp năng lượng Titan / 🧱buff giáp MAX | Nâng cấp Lv.1-100',
  'ATK ×{a}/หมัด (รวม ×{b})':'ATK ×{a}/đòn (tổng ×{b})',
  'หลบหลีก':'Né tránh',
  'ทุก 3 AGI = หลบ +1% · เพดาน 75% · มอนเลเวลสูงลดโอกาส':'Mỗi 3 AGI = +1% né · trần 75% · quái Lv cao làm giảm',
  '+1m รัศมี · +0.025 ตัวคูณ':'+1m bán kính · +0.025 hệ số',
  'ใช้ครั้งละ 49 P — คืนแต้ม Ragnalok ที่ลงไปทั้งหมด กลับมาอัพใหม่ได้ (ไม่มีฟรีรายวัน)':'49 P mỗi lần — hoàn lại toàn bộ điểm Ragnalok đã cộng để cộng lại (không có lượt miễn phí mỗi ngày)',
  '→ ได้รับ <b style="color:#b45309">{a} Ragnalok Points</b> คืน (Lv/EXP ไม่หาย)':'→ Nhận lại <b style="color:#b45309">{a} Điểm Ragnalok</b> (Lv/EXP giữ nguyên)',
  'ยืนยัน Reset แต้ม Ragnalok? (หัก 49 P · ได้ {a} แต้มคืน)':'Xác nhận reset điểm Ragnalok? (trừ 49 P · hoàn {a} điểm)',
  'ทุกอาวุธ':'Mọi Vũ Khí',
  'แต้มค้าง {n}':'Điểm còn lại {n}',
  'อัพ 1 แต้ม = +0.1% · บวกทับค่า final โดยตรง':'1 điểm = +0.1% · cộng thẳng vào giá trị cuối',
  'ATK โบนัส (ทุกอาวุธ)':'ATK Cộng Thêm (mọi vũ khí)',
  'ตีบวก':'Cường hóa',
  'ทุก 10 pt (LUK+STR) = คริ +1% · เพดาน 50%':'Mỗi 10 pt (LUK+STR) = +1% chí mạng · trần 50%',
  'ไอเทมพิเศษที่ Drop จาก MVP มีผลเสริม Passive ให้ตัวละครเมื่อครอบครอง':'Vật phẩm đặc biệt rơi từ MVP. Chỉ cần sở hữu là nhân vật nhận thưởng passive.',
  'ชิ้นส่วนเสริม Robot เมื่อครบชุดจะ Unlock ความสามารถพิเศษให้ไททัน':'Linh kiện gắn thêm cho Robot. Đủ bộ sẽ mở khả năng đặc biệt cho Titan.',
  'ชิ้นส่วนอาวุธขว้าง':'Linh kiện phi dao',
  'เพิ่มความแรงของมีดขว้าง เช่น เพิ่มระยะขว้าง / ความจุสูงสุด':'Tăng sức mạnh phi dao — vd. thêm tầm ném / sức chứa tối đa.',
  'ใช้อัปเกรดยานบิน เพิ่มความสามารถการผลิตของยานบิน':'Dùng nâng cấp phi thuyền, tăng năng lực sản xuất.',
  'ชิ้นส่วน Stat':'Linh kiện Stat',
  'เสริม Stat ให้ตัวละครโดยตรงเมื่อครอบครอง':'Cộng thẳng Stat cho nhân vật khi sở hữu.',
  'Equipment (สวมใส่)':'Equipment (mặc trên người)',
  'หมวก / เกราะ / ถุงมือ / รองเท้า / แหวน / สร้อย แต่ละชิ้นมีหลาย Tier ยิ่ง Tier สูงยิ่งแรง':'Mũ / giáp / găng / giày / nhẫn / dây chuyền — mỗi món có nhiều tier, tier càng cao càng mạnh.',
  'ระดับสีของ Item':'Cấp màu vật phẩm',
  'ขาว < เขียว < ฟ้า < ม่วง < ทอง < แดง ยิ่งหายากยิ่งแรงและมีราคาสูงในตลาด':'Trắng < Xanh lá < Xanh dương < Tím < Vàng < Đỏ — càng hiếm càng mạnh và càng được giá ở chợ.',
  'ยานบิน (House)':'Phi thuyền (House)',
  'สร้างยานบิน':'Sở hữu phi thuyền',
  'ยานบินสร้างอัตโนมัติเมื่อ Level ถึงขั้นต่ำที่กำหนด ตำแหน่งสุ่มห่างจากผู้เล่นคนอื่นอย่างน้อย 10m':'Phi thuyền tự được xây khi đạt cấp tối thiểu, vị trí ngẫu nhiên cách người chơi khác ít nhất 10m.',
  'อัปเกรดยานบิน':'Nâng cấp phi thuyền',
  'ใช้ทรัพยากร 🪵ไม้ / 🪨หิน / ⚙️เหล็ก / 🟫ทองแดง เพิ่ม Level ยานบินเพื่อปลดล็อคการผลิต T สูงขึ้น':'Dùng tài nguyên 🪵gỗ / 🪨đá / ⚙️sắt / 🟫đồng để nâng cấp phi thuyền, mở sản xuất T cao hơn.',
  'ผลิตได้ 6 ระดับต่อชนิดอาวุธ เปิด/ปิดแต่ละ T แยกกัน\nใช้ ⚙️เหล็ก (1/2/5/8/12/15 ต่อ T1-T6) + 🟫ทองแดง + ⚡1/นัด (ทุก T)\nทองแดง = เหล็ก × ตามชนิด: มีดสั้น ×1.0, ธนูไททัน ×1.25, มีดยาว ×1.5':'Sản xuất 6 tier mỗi loại vũ khí; bật/tắt từng T riêng\nTốn ⚙️sắt (1/2/5/8/12/15 cho T1-T6) + 🟫đồng + ⚡1/viên (mọi T)\nĐồng = sắt × theo loại: dao găm ×1.0, cung Titan ×1.25, dao dài ×1.5',
  'ยา T1-T6':'Thuốc T1-T6',
  'ผลิตได้ 6 ระดับ (+30 ถึง +400 HP) ต้นทุน 🌿×5-30 ต่อขวด + ⚡3/ขวด\nHP < 30% กินเสมอแม้ปิด AUTO, threshold 30-90% ปรับได้':'Sản xuất 6 tier (+30 đến +400 HP). Chi phí 🌿×5-30 mỗi bình + ⚡3/bình\nHP < 30% luôn uống kể cả tắt AUTO; ngưỡng 30-90% chỉnh được',
  'พลังงานยานบิน (⚡)':'Năng lượng phi thuyền (⚡)',
  'ได้จาก 3 ทาง: ยาน Orion passive (lv×20⚡/นาที), เผาไม้ (Lv.1=88⚡/เผา ×4), Solar Cell (passive, lv×27⚡/นาที)\nใช้ผลิตกระสุน/ยา และชาร์จ Robot ด้วย':'Đến từ 3 nguồn: tàu Orion passive (lv×20⚡/phút), đốt gỗ (Lv.1=88⚡/lần ×4), Solar Cell (passive, lv×27⚡/phút)\nDùng để sản xuất đạn/thuốc và sạc Robot luôn',
  'ผลิตพลังงานอัตโนมัติทุกนาที ไม่ต้องใช้ไม้ stack กับการเผาไม้\nอัพเกรดด้วย 🪨หิน + 🟫ทองแดง':'Tự tạo năng lượng mỗi phút — không cần gỗ, cộng dồn với đốt gỗ\nNâng cấp bằng 🪨đá + 🟫đồng',
  'Premium Titan Beam ยานบิน':'Premium Titan Beam phi thuyền',
  'ป้องกันอัตโนมัติรอบยานบิน ใช้พลังงานยานบิน -25⚡/นัด (เพิ่มตามเลเวล Premium Titan Beam)\nอัพเกรดด้วย 🪨หิน + 💰Gold เพิ่ม ATK และระยะ':'Tự phòng thủ quanh phi thuyền, tốn năng lượng phi thuyền -25⚡/phát (tăng theo cấp Premium Titan Beam)\nNâng cấp bằng 🪨đá + 💰Gold để tăng ATK và tầm',
  'ยานบินผู้เล่นอื่น':'Phi thuyền người chơi khác',
  'เห็นยานบินเพื่อนบนแผนที่เป็นยานลำเล็กสีจาง พร้อมชื่อเจ้าของ':'Phi thuyền của bạn bè hiện trên bản đồ dạng tàu nhỏ màu nhạt kèm tên chủ.',
  'ตลาด (Market)':'Chợ (Market)',
  'วางขาย':'Rao bán',
  'เลือกของจากกระเป๋า ตั้งราคา/ชิ้น วางขายได้สูงสุด 5 รายการพร้อมกัน ของจะถูกดึงออกจากกระเป๋าทันที':'Chọn đồ từ túi, đặt giá mỗi món. Rao tối đa 5 tin cùng lúc; đồ bị rút khỏi túi ngay khi rao.',
  'ซื้อของ':'Mua đồ',
  'ดูรายการของที่ผู้เล่นอื่นวางขาย กรองตามหมวดหรือค้นหาชื่อ Badge "ใหม่ ✨" = ของที่คุณยังไม่มี':'Xem đồ người chơi khác rao bán; lọc theo mục hoặc tìm theo tên. Badge "Mới ✨" = đồ bạn chưa có.',
  'ของฉัน':'Tin của tôi',
  'ดูรายการที่ตัวเองวางขายอยู่ กด "ยกเลิก" เพื่อดึงของกลับ':'Xem các tin mình đang rao. Bấm "Hủy" để lấy lại đồ.',
  'บันทึกทุก transaction ทั้งซื้อและขาย กรองดูแต่ละประเภทได้ แสดง Gold +/- ของแต่ละรายการ':'Ghi lại mọi giao dịch mua lẫn bán. Lọc theo loại; hiển thị Gold +/- từng mục.',
  'ค่า Fee':'Phí',
  'ผู้ขายถูกหัก 5% ของราคาขาย เป็นค่าธรรมเนียมตลาด':'Người bán bị trừ 5% giá bán làm phí chợ.',
  'อายุ Listing':'Thời hạn tin rao',
  'ของที่วางขายจะหมดอายุใน 24 ชั่วโมง หากไม่มีคนซื้อต้อง cancel เพื่อรับของคืน':'Tin rao hết hạn sau 24 giờ. Không ai mua thì phải hủy tin để nhận lại đồ.',
  'EXP ที่ได้จากการต่อสู้เพิ่มขึ้น เหมาะช่วงที่อยากเลเวลขึ้นเร็ว':'Tăng EXP nhận từ chiến đấu — hợp lúc muốn lên cấp nhanh.',
  'Gold ที่ได้จาก Drop เพิ่มขึ้น ช่วยสะสมทองสำหรับใช้ในตลาด':'Tăng Gold từ drop, giúp tích vàng xài ở chợ.',
  'ตัวละครขุด Resource (Wood/Stone/Iron/Copper) ได้เพิ่มขึ้น ช่วยอัปเกรดยานบินเร็วขึ้น':'Nhân vật đào tài nguyên (Wood/Stone/Iron/Copper) nhiều hơn, nâng cấp phi thuyền nhanh hơn.',
  'สกุลเงิน Premium ซื้อด้วยเงินจริง กดเมนู Premium เพื่อดูแพ็กเกจ':'Tiền tệ Premium mua bằng tiền thật. Mở menu Premium để xem các gói.',
  // ── Onboarding (showOnboarding) ──
  'ยินดีต้อนรับสู่ Ragnalok':'Chào mừng đến Ragnalok',
  'นี่คือเกม <b>idle RPG</b> — ตัวละครของคุณ <b style="color:#facc15">ต่อสู้อัตโนมัติ</b><br>เพียงพาไปอยู่ใกล้มอนสเตอร์ ก็ยิงเองทันที<br><br>หน้าที่ของคุณคือ <b>วางแผน · อัพเกรด · สำรวจ</b> ให้แข็งแกร่งขึ้น':'Đây là game <b>idle RPG</b> — nhân vật của bạn <b style="color:#facc15">tự động chiến đấu</b><br>Chỉ cần đến gần quái là tự bắn ngay<br><br>Việc của bạn là <b>lên kế hoạch · nâng cấp · khám phá</b> để mạnh hơn',
  'การเคลื่อนที่':'Di chuyển',
  '• <b>🤖 AUTO ON</b> — ให้ตัวละครเดินหามอนและสู้เอง<br>• <b>ปุ่มลูกศร (D-pad)</b> — บังคับเดินเอง 8 ทิศ กด ✕ เพื่อหยุด<br>• <b>🔒 LOCK ATK</b> — ยืนนิ่งกับที่ แล้วขว้างใส่มอนในระยะ<br>• ปรับ <b>รัศมีสำรวจ</b> ได้ที่แถบใต้ปุ่ม AUTO':'• <b>🤖 AUTO ON</b> — nhân vật tự tìm quái và tự đánh<br>• <b>Nút mũi tên (D-pad)</b> — tự đi 8 hướng, bấm ✕ để dừng<br>• <b>🔒 LOCK ATK</b> — đứng yên tại chỗ và ném vào quái trong tầm<br>• Chỉnh <b>bán kính khám phá</b> ở thanh dưới nút AUTO',
  'ต่อสู้ & ฟื้นฟู':'Chiến đấu & hồi phục',
  '• ระบบเล็งมอนใกล้สุดให้เอง สลับมีดสั้น/มีดยาว ตามระยะอัตโนมัติ<br>• กระสุนหมด → ใช้มีดอัตโนมัติ<br>• ตั้ง <b>กินยาอัตโนมัติ</b> ได้ในแท็บ 🎒 ไอเทม (HP &lt; 30% กินเสมอ)':'• Hệ thống tự nhắm quái gần nhất, tự đổi dao găm/dao dài theo tầm<br>• Hết đạn → tự chuyển sang dao<br>• Đặt <b>tự uống thuốc</b> trong tab 🎒 Vật phẩm (HP &lt; 30% luôn uống)',
  'ทำให้เก่งขึ้น':'Trở nên mạnh hơn',
  ['แท็บด้านล่างคือหัวใจของเกม:<br>• 📊 <b>Stat</b> — ใส่แต้มเพิ่มพลัง (เลเวลอัพได้แต้ม)<br>• '+_VI_KNIFE_S+' <b>มีดสั้น</b> — อัพเลเวลเพิ่ม ATK/ระยะ<br>• 🐱 <b>ผู้ติดตาม</b> — ไททัน/เนโกะ/Premium Delivery ช่วยสู้และส่งของ<br>• 🛸 <b>ยานบิน</b> — เก็บของ ผลิตกระสุน ยิงสนับสนุน']:'Các tab bên dưới là trái tim của game:<br>• 📊 <b>Stat</b> — cộng điểm tăng sức mạnh (lên cấp có điểm)<br>• '+_VI_KNIFE_S+' <b>Dao găm</b> — nâng cấp tăng ATK/tầm<br>• 🐱 <b>Đồng hành</b> — Titan/Neko/Premium Delivery phụ đánh và giao đồ<br>• 🛸 <b>Phi thuyền</b> — chứa đồ, sản xuất đạn, bắn yểm trợ',
  'พร้อมลุยแล้ว!':'Sẵn sàng quẩy!',
  '• ⚡ ออฟไลน์ก็ได้รางวัล (สูงสุด 3 ชม.)<br>• เก็บ <b>ของสะสม</b> เพิ่มโบนัส · ซื้อขายใน <b>ตลาด</b><br>• อยากรู้ลึก กดปุ่มกลม <b>📖</b> มุมซ้ายบนของแผนที่ (ใต้ไอคอน FB) ได้ตลอดเวลา<br><br><b style="color:#34d399">ขอให้สนุกกับการผจญภัย!</b>':'• ⚡ Offline vẫn có thưởng (tối đa 3 giờ)<br>• Gom <b>đồ sưu tầm</b> nhận thưởng · mua bán ở <b>Chợ</b><br>• Muốn tìm hiểu sâu, bấm nút tròn <b>📖</b> góc trên trái bản đồ (dưới icon FB) bất cứ lúc nào<br><br><b style="color:#34d399">Chúc phiêu lưu vui vẻ!</b>',
  'เริ่มต้นเล่น':'Bắt đầu chơi',
  'ข้าม ✕':'Bỏ qua ✕',
  'ย้อน':'Quay lại',
  'ถัดไป →':'Tiếp →',
  '📖 ดูคู่มือเต็ม':'📖 Cẩm nang đầy đủ',
  'เริ่มเล่น! ⚔️':'Chơi thôi! ⚔️',
  // ── ชื่อมอนสเตอร์ (ตรงกับ name ใน xhrpg_monsters_master — MVP ใช้ชื่อเดียวกัน) ──
  'กระต่ายป่า':'Thỏ hoang', 'งูพิษ':'Rắn độc', 'หมูป่า':'Heo rừng', 'หมาป่า':'Sói', 'หมีป่า':'Gấu hoang',
  'ยักษ์หิน':'Khổng lồ đá', 'อัศวินมืด':'Hắc kỵ sĩ', 'ราชาค้างคาว':'Vua dơi', 'ยักษ์หิมะ':'Khổng lồ tuyết', 'สุนัข':'Chó',
  'ไก่เจี๊ยบ':'Gà con', 'ลูกหมู':'Heo con', 'ลูกแกะ':'Cừu con', 'ไก่ป่า':'Gà rừng', 'ไก่งวง':'Gà tây',
  'ลูกวัว':'Bê con', 'แกะ':'Cừu', 'วัว':'Bò', 'พญากระทิง':'Vua bò tót',
  'หมีสนาม':'Gấu đồng', 'ลิงป่า':'Khỉ rừng', 'นกเหยี่ยวน้อย':'Diều hâu non', 'อินทรีเวหา':'Đại bàng trời', 'นกฮูกรัตติกาล':'Cú đêm',
  'สไลม์เขียว':'Slime xanh lá', 'สไลม์น้ำเงิน':'Slime xanh dương', 'ราชาสไลม์ม่วง':'Vua Slime tím',
  'สไลม์เหลือง':'Slime vàng', 'สไลม์ส้ม':'Slime cam', 'ราชาสไลม์แดง':'Vua Slime đỏ',
  'หน่อพิษ':'Mầm độc', 'พืชนักล่า':'Cây ăn thịt', 'ราชาพืชมืด':'Vua cây bóng tối',
  'โกเลมหิน':'Golem đá', 'โกเลมศิลา':'Golem đá tảng', 'โกเลมโบราณ':'Golem cổ đại',
  'เห็ดสปอร์':'Nấm bào tử', 'เห็ดพิษแดง':'Nấm độc đỏ', 'เห็ดม่วงมรณะ':'Nấm tím tử thần',
  'หนูทราย':'Chuột cát', 'หนูยักษ์':'Chuột khổng lồ', 'ราชาหนู':'Vua chuột',
  'คนกิ้งก่า':'Người thằn lằn', 'นักรบกิ้งก่า':'Chiến binh thằn lằn', 'ราชากิ้งก่า':'Vua thằn lằn',
  'คนหมาป่า':'Người sói', 'นักรบหมาป่า':'Chiến binh sói', 'ราชาหมาป่า':'Vua sói',
  'สไลม์พิษ':'Slime độc', 'สไลม์ยักษ์':'Slime khổng lồ', 'ราชาสไลม์':'Vua Slime',
  'แวมไพร์หนุ่ม':'Ma cà rồng trẻ', 'แวมไพร์อาวุโส':'Ma cà rồng trưởng lão', 'ลอร์ดแวมไพร์':'Chúa tể ma cà rồng',
  'โครงกระดูกทหาร':'Lính xương', 'โครงกระดูกอัศวิน':'Kỵ sĩ xương', 'ขุนพลกระดูก':'Tướng quân xương',
  'ปีศาจน้อย':'Tiểu quỷ', 'ปีศาจสงคราม':'Quỷ chiến tranh', 'จอมมารอสูร':'Chúa tể ác quỷ',
  'ซอมบี้เดินดิน':'Zombie đất', 'ซอมบี้นักรบ':'Zombie chiến binh', 'ซอมบี้หัวหน้าฝูง':'Vua Zombie',
  'แมงกะพรุนเรืองแสง':'Sứa phát quang', 'แมงกะพรุนพิษ':'Sứa độc', 'ราชาแมงกะพรุน':'Vua sứa',
  'ปูหินยักษ์':'Cua đá khổng lồ', 'ปูเกราะเหล็ก':'Cua thiết giáp', 'เม่นทะเลหนามพิษ':'Cầu gai độc',
  'ปลาปะการังพิษ':'Cá san hô độc', 'ปลาสิงโตทะเล':'Cá sư tử', 'ปลาปีศาจใต้สมุทร':'Cá quỷ',
  'ฉลามหิวโหย':'Cá mập đói', 'ฉลามหัวค้อน':'Cá mập búa', 'เจ้าสมุทรใต้ทะเลลึก':'Thủy quái vực sâu',
  'มังกรเพลิงโบราณ':'Hỏa long cổ đại', 'มังกรทองคำ':'Kim long', 'มังกรโลหิต':'Huyết long',
  'ตาปีศาจซีด':'Ma nhãn xám', 'ตาปีศาจเพลิง':'Hỏa ma nhãn', 'ราชาตาปีศาจ':'Vua ma nhãn',
  'ซาลาแมนเดอร์เพลิง':'Kỳ nhông lửa', 'ปีศาจน้อยเพลิง':'Tiểu quỷ hỏa', 'ปีศาจน้อยเงามืด':'Tiểu quỷ bóng tối',
  'หมาล่าเนื้อเพลิง':'Chó săn lửa', 'กะโหลกเพลิง':'Đầu lâu lửa', 'อัศวินเพลิงนิรันดร์':'Kỵ sĩ hỏa ngục',
  'จอมมารรัตติกาล':'Ma Vương Bóng Đêm', // MVP หน้าเดโม
  'ระยะ {a} +{b}':'Tầm {a} +{b}', 'ความจุกระสุน +{a}':'Sức chứa đạn +{a}', 'ตีไททัน -{d}⚡ (เหลือ {e})':'đánh Titan -{d}⚡ (còn {e})', // แท็บ MVP pattern
  // 🏟️ ดันท้าบอส (Boss Arena)
  'ดันท้าบอส — 1 ต่อ 1':'Đấu Trường Boss — 1 vs 1',
  // 📊 ค่ากลางระบบ
  'ค่ากลางระบบ (ใช้ร่วมทุกอาวุธ)':'Giá trị hệ thống chung (dùng cho mọi vũ khí)',
  'บวกเท่ากันไม่ว่าถืออาวุธอะไร · ATK พื้นฐานของอาวุธแต่ละชนิดดูในเมนูอาวุธ':'Như nhau dù dùng vũ khí gì · ATK gốc từng vũ khí xem trong menu vũ khí',
  'ATK (โมดูล)':'ATK (mô-đun)', 'CRIT (คริ ×2)':'CRIT (dmg ×2)', 'โมดูลทุกอาวุธ':'mô-đun mọi vũ khí', 'จาก {a}':'từ {a}',
  'HP สูงสุด':'HP tối đa', 'MP สูงสุด':'MP tối đa',
  // 📊 แผงช่วยเหลือ STAT
  'STR — พละกำลัง':'STR — Sức mạnh', 'AGI — ความว่องไว':'AGI — Nhanh nhẹn', 'DEX — ความแม่นยำ':'DEX — Khéo léo',
  'INT — สติปัญญา':'INT — Trí tuệ', 'VIT — ความอึด':'VIT — Thể lực', 'LUK — โชค':'LUK — May mắn',
  'ATK ดาบ (melee) +3 ต่อ STR (เกิน 5)\n🛡️ เกราะสูงสุด +1 ทุก 2 STR (เกิน 5) — แบบ VIT\n💥 โอกาส Crit +1% ทุก 10 STR (รวมกับ LUK · ส่วนสเตตัสรวมสูงสุด 50%)\n(ความจุกระสุนอิงเลเวลผู้เล่น — ดูเมนูอาวุธ)':'ATK kiếm (cận chiến) +3 mỗi STR (trên 5)\n🛡️ Giáp tối đa +1 mỗi 2 STR (trên 5) — như VIT\n💥 Tỉ lệ Crit +1% mỗi 10 STR (gộp với LUK · phần chỉ số tối đa 50%)\n(Sức chứa đạn theo Lv người chơi — xem menu vũ khí)',
  'เพิ่มความเร็วเดิน (ตาม AGI)\nหลบมอน = floor(AGI/3) − (เลเวลมอน−1) %\nเพดานหลบ 75% · MVP หลบยากเท่าตัว\n⏱️ ลด CD สกิลทุกตัว = AGI/6 % (สูงสุด 50% ที่ AGI 300)':'Tăng tốc độ di chuyển (theo AGI)\nNé = floor(AGI/3) − (Lv quái−1) %\nGiới hạn né 75% · MVP khó né gấp đôi\n⏱️ Giảm CD mọi kỹ năng = AGI/6 % (tối đa 50% tại AGI 300)',
  'ATK ขว้างมีดสั้น (ใกล้) +2.0 ต่อ DEX (เกิน 5)\nATK ขว้างมีดยาว (ไกล) +2.5 ต่อ DEX (เกิน 5)\nระยะขว้าง +1m ทุก 24 DEX (= DEX/24 ม.)':'ATK phi dao găm (gần) +2.0 mỗi DEX (trên 5)\nATK phi dao dài (xa) +2.5 mỗi DEX (trên 5)\nTầm ném +1m mỗi 24 DEX (= DEX/24 m)',
  'MP สูงสุด = 50 + INT×5\nMP ฟื้น = 2 + floor(INT/5) ต่อ tick\nช่วยฟื้นพลังงานไททัน +floor(INT/10) /วิ\nATK ป้อม (Turret) +3 ต่อ INT (ป้อมทุกตัว)':'MP tối đa = 50 + INT×5\nHồi MP = 2 + floor(INT/5) mỗi tick\nHồi năng lượng Titan +floor(INT/10) /giây\nATK trụ (Turret) +3 mỗi INT (mọi trụ)',
  'HP สูงสุด = +2 ต่อแต้ม VIT ที่ลง\nเกราะสูงสุด = 100 + floor((VIT−5)/5)\nเกราะฟื้น = max(1, floor(VIT/10)) ต่อวินาที\nHP ฟื้น = floor(VIT/5) ต่อวินาที\nความจุยา +2 ต่อ VIT (ต่อระดับยา T1-T6)':'HP tối đa = +2 mỗi điểm VIT đã cộng\nGiáp tối đa = 100 + floor((VIT−5)/5)\nHồi giáp = max(1, floor(VIT/10)) mỗi giây\nHồi HP = floor(VIT/5) mỗi giây\nSức chứa bình máu +2 mỗi VIT (mỗi bậc T1-T6)',
  '💥 โอกาส Crit ×2 = floor((LUK+STR)/10)% (LUK+STR รวมกัน · สูงสุด 50%) · คริทุกอาวุธ\nโอกาสดรอปทรัพยากร/สมุนไพร = min(48, 24 + floor(LUK/5)×0.75)% (ฐาน 25% ที่ LUK5 · ไม้ ×2)\nโบนัสจำนวน: 30% ลุ้นได้เพิ่มสุ่ม 1..floor(LUK/15) (เริ่มมีผลที่ LUK15)\nเดินสำรวจ: ขุดเจอของ min(40, 14+floor(LUK/5)×0.7)% · เจอไม้เพิ่มตาม LUK (เพดาน 37%)\nไม่มีผลกับ ทอง/การ์ด/โมดูล/เพชร':'💥 Tỉ lệ Crit ×2 = floor((LUK+STR)/10)% (LUK+STR gộp · tối đa 50%) · crit mọi vũ khí\nTỉ lệ rơi tài nguyên/thảo dược = min(48, 24 + floor(LUK/5)×0.75)% (gốc 25% tại LUK5 · gỗ ×2)\nThưởng số lượng: 30% cơ hội +1..floor(LUK/15) ngẫu nhiên (từ LUK15)\nKhám phá: đào được min(40, 14+floor(LUK/5)×0.7)% · thêm gỗ theo LUK (trần 37%)\nKhông ảnh hưởng vàng/thẻ/mô-đun/đá quý',
  'หน้า {a}/{b}':'Trang {a}/{b}',
  '⏩ Skip {n} ติดกัน 5 ครั้ง?\n🎫 รวม {c} (หยุดเองถ้าโควตา/P หมด)':'⏩ Skip {n} 5 lần liên tiếp?\n🎫 Tổng {c} (dừng nếu hết lượt/P)',
  'บัตร 1,000G × Lv บอส · รางวัลฟรี 3 ครั้ง/วัน · แพ้ไม่นับสิทธิ์':'Vé 3.000G × Lv boss · 3 phần thưởng miễn phí/ngày · thua không tính',
  'ฟรีวันนี้เหลือ':'Miễn phí hôm nay', 'ซื้อด้วย P ได้อีก':'Lượt P còn lại',
  '⚔️ กำลังสู้บอสอยู่ — กลับไปดูในแมพ!':'⚔️ Đang đánh boss — xem trên bản đồ!',
  'ยังไม่มีบอสให้ท้า (ต้อง Lv สูงกว่าบอสอย่างน้อย 10)':'Chưa có boss để thách đấu (cần hơn boss 10 Lv)',
  'ชนะแล้ววันนี้ — Skip รับรางวัลทันที':'Đã thắng hôm nay — Skip nhận thưởng ngay',
  'ปลดที่ Lv.{a}':'Mở ở Lv.{a}',
  'เข้าดันสู้ {n} Lv.{lv}?\n🎫 ค่าบัตร {c} (แพ้ไม่คืน ไม่นับสิทธิ์)':'Đánh {n} Lv.{lv}?\n🎫 Vé {c} (thua không hoàn, không tính lượt)',
  '⏩ Skip รับรางวัล {n} ทันที?\n🎫 ค่าบัตร {c}':'⏩ Nhận thưởng {n} ngay?\n🎫 Vé {c}',
  '(ไม่มีของดรอปรอบนี้ — ได้ EXP/G)':'(không có đồ rơi lần này — chỉ EXP/G)',
  'รางวัลจากบอส {n}':'Phần thưởng từ boss {n}', 'เยี่ยม! ไปตีต่อ':'Tuyệt! Đánh tiếp',
  'ประวัติรางวัล — {n}':'Lịch sử phần thưởng — {n}',
  'ยังไม่มีประวัติ — ชนะบอสตัวนี้ครั้งแรกกันเลย!':'Chưa có lịch sử — hãy thắng boss này lần đầu!',

  // ── Hệ thống Nông Trại (Home Farm) ──
  'องุ่นป่า':'Nho dại', 'ถั่วเลื้อย':'Đậu leo', 'พริกแดง':'Ớt đỏ', 'กะหล่ำปลี':'Bắp cải', 'ดอกมันเทศ':'Hoa khoai lang',
  'ใบหยก':'Lá ngọc', 'ว่านหนาม':'Lô hội gai', 'ข้าวสาลี':'Lúa mì', 'แอปเปิล':'Táo', 'เลมอน':'Chanh vàng',
  'เชอร์รี่':'Anh đào', 'มะพร้าว':'Dừa', 'เกรดทอง':'Đặc biệt (Vàng)', 'ชิ้น':'chiếc',
  'ฟาร์มของฉัน':'Nông trại của tôi', 'แปลงปลูกเปิดแล้ว {a}/6':'Đã mở {a}/6 plots đất',
  'แปลงถัดไปปลดที่บ้าน Lv.{a}':'Plot tiếp theo mở ở nhà Lv.{a}',
  'อัพเกรด nhà':'Nâng cấp nhà', 'อัพเกรดบ้าน':'Nâng cấp nhà',
  'อัพเกรดเป็น Lv.{a}':'Nâng cấp lên Lv.{a}',
  'เรทปกติ ×10 · ใช้ทุกทรัพยากร':'tỷ lệ thường ×10 · tiêu tốn mọi tài nguyên',
  'อัพได้สูงสุด Lv.{a} ที่ผู้เล่น Lv.{b}':'Nâng tối đa Lv.{a} ở Lv người chơi {b}',
  'ปลูกแล้ว {a}/{b} หลุม':'Đã trồng {a}/{b} luống',
  'ต้นถัดไปสุกใน {a} นาที':'cây tiếp theo chín sau {a} phút',
  'เก็บเกี่ยว+ขาย ({a} หลุมสุก)':'Thu hoạch + bán ({a} luống chín)',
  'ยังไม่มีเมล็ด — เมล็ดดรอปจากการล่ามอนสเตอร์ (ทุกระดับ)':'Chưa có hạt giống — hạt giống rơi ra khi săn quái (mọi cấp độ)',
  '🌱 เมล็ดพืช':'🌱 Hạt giống', 'รวม {a} เมล็ด':'Tổng cộng {a} hạt',
  'เมล็ดดรอปจากการล่ามอนสเตอร์ทุกระดับ · เอาไปปลูกที่ 🏡 บ้านของฉัน (ปุ่มบ้านซ้ายจอ) — สุกแล้วเก็บขายได้ G':'Hạt giống rơi khi săn quái mọi cấp độ · đem trồng tại 🏡 Nông trại (nút Nhà góc trái) — chín thì thu hoạch bán lấy G',
  'เยี่ยมบ้าน':'Ghé thăm', 'บ้านของ {a}':'Nhà của {a}', 'ของสะสมหายาก':'Đồ sưu tầm quý hiếm', 'แปลงปลูก':'Luống đất',
  'ดูอย่างเดียว — ของในบ้านเป็นของเจ้าของบ้าน':'Chỉ xem — tất cả vật phẩm ở đây thuộc về chủ nhà',
  'เข้าไปเดินในบ้าน':'Đi vào trong nhà', '🏡 เข้าเยี่ยมบ้านเพื่อนแล้ว — ดูอย่างเดียว':'🏡 Đã ghé thăm nhà bạn — chỉ xem',
  'ไม่พบบ้านของผู้เล่นคนนี้':'Không tìm thấy nhà của người chơi này', 'ออก':'Rời đi',
  '🏡 กำลังเยี่ยมบ้านเพื่อน — จัดการได้เฉพาะบ้านตัวเอง':'🏡 Đang thăm nhà bạn — chỉ có thể quản lý nhà của mình',
  'กำลังเยี่ยมบ้านของ {a}':'Đang thăm nhà của {a}', 'เข้าบ้านไม่ได้ขณะอยู่ในสนามประลอง':'Không thể vào nhà khi đang ở Đấu trường Colosseum',
  'บ้านของฉัน':'Nhà của tôi',
  'ประวัติปล้น':'Lịch sử cướp',
  'โควตาปล้นวันนี้ {a}/{b}':'Lượt cướp hôm nay {a}/{b}',
  'บุกปล้น':'Tấn công cướp',
  'บุกปล้นบ้าน {a}? (ใช้โควตา 1 ครั้ง · ต้องผ่านยาม+ดวลเจ้าของ)':'Tấn công cướp nhà {a}? (Dùng 1 lượt · phải thắng lính canh + chủ nhà)',
  'ปล้นบ้านคนอื่น':'Đi cướp nhà khác',
  'ปล้นบ้านล่าสุด':'Cướp nhà gần đây',
  'โดนปล้น':'Bị cướp',
  'ไปปล้น':'Đi cướp',
  'ยังไม่มีประวัติปล้น':'Chưa có lịch sử cướp',
  'ปิดหน้าต่าง':'Đóng cửa sổ',
  'ยังไม่มีบ้านที่ปลูกผักให้ปล้นตอนนี้':'Chưa có nhà nào trồng rau để cướp lúc này',
  'บุกเข้าบ้านเป้าหมาย...':'Đang đột nhập vào nhà mục tiêu...',
  'ปล้นไม่ได้: ':'Không thể cướp: ',
  'ปล้นบ้านเพื่อน':'Cướp nhà bạn bè',
  'กำลังโหลด...':'Đang tải...',
  'โหลดไม่สำเร็จ':'Tải thất bại',
  'ระบบยังไม่พร้อม — แจ้งแอดมิน':'Hệ thống chưa sẵn sàng — vui lòng báo Admin',
  'ติดโล่คุ้มกัน':'Có khiên bảo vệ',
  'ปล้นวันนี้แล้ว':'Hôm nay đã cướp rồi',
  'บ้านนี้เต็มโควตา':'Nhà này đã bị cướp hết lượt',
  'โควตาคุณหมด':'Bạn đã hết lượt cướp',
  'พร้อมเก็บ':'Sẵn sàng thu hoạch',
  'กำลังโต':'Đang lớn',
  'ถอด (ไข่หายถาวร)':'Gỡ bỏ (Mất trứng vĩnh viễn)',
  'ถอน':'Gỡ bỏ',
  'ใส่ยาม':'Đặt lính canh',
  'ต้องการมอนสเตอร์ระดับปกติ 1 ตัว':'Cần 1 quái vật cấp thường',
  'ต้องการมอนสเตอร์ระดับ MVP 1 ตัว':'Cần 1 quái vật cấp MVP',
  'ไม่มีมอนสเตอร์ (ต้องมีไข่ในคลังก่อน)':'Không có quái vật (phải có trứng trong kho trước)',
  'ใส่':'Đặt',
  'ถอด':'Gỡ',
  'ยามบ้าน':'Lính canh nhà',
  'ยาม':'Lính canh',
  'ใส่ไข่มอนสเตอร์ในช่องเพื่อเฝ้าบ้าน ป้องกันคนอื่นมาปล้นผัก':'Đặt trứng quái vật vào ô để gác nhà, chống kẻ khác đến cướp rau',
  'มอนธรรมดาป้องการปล้น T1-T3 · มอน MVP ป้องกัน T4-T6 (ถอดแล้วไข่หายถาวร!)':'Quái thường bảo vệ T1-T3 · Quái MVP bảo vệ T4-T6 (gỡ ra mất trứng vĩnh viễn!)',
};

